### DISCUSSION TITLE
Not able to to deploy an application

### DISCUSSION THREAD

**Discussion by junoriosity** [kubeapps/kubeapps#4320] [Q&A] [answered]
As mentioned earlier (https://github.com/kubeapps/kubeapps/discussions/4219) I deployed kubeapps with 

```
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-crds.yaml
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-resources.yaml

cat <<EOF | kubectl apply -f -
kind: JWTAuthenticator
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
metadata:
  name: jwt-authenticator
spec:
  issuer: https://my-auth.eu.auth0.com/
  audience: my-client-id
  claims:
    groups: groups
    username: email
EOF

cat <<EOF | kubectl apply -f -
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: test@test.com
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubeapps-operators
EOF

kubectl create ns kubeapps
helm install kubeapps bitnami/kubeapps --namespace kubeapps -f myvals.yaml 
```

where `myvals.yaml` is

```
useHelm3: true
authProxy:
  additionalFlags:
    - --oidc-issuer-url=https://my-auth.eu.auth0.com/ # Example: https://antoniogamez.eu.auth0.com/  # mind the last "/" character
  # If you are using a different ingress config, you might need to tweak these flags. More info in the "oauth2-proxy" official docs
    - --redirect-url=http://127.0.0.1:3000/oauth2/callback
    # - --cookie-domain=localhost
    # - --whitelist-domain=localhost
    # - --cookie-secure=false
  clientID: my-client-id
  clientSecret: my-client-secret
  cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
  enabled: true
  provider: oidc

pinnipedProxy:
  enabled: true # if using Pinniped, you'll need to enable this option here
#  defaultAuthenticatorType: jwt
#  defaultAuthenticatorName: jwt-authenticator

clusters:
  - name: default
    apiServiceURL: https://... # impersonation proxy URL
    certificateAuthorityData: ... #  impersonation proxy CA
    pinnipedConfig:
      enabled: true
```

With this I can reach the catalog panel

<img width="1649" alt="kubeapps_catlog" src="https://user-images.githubusercontent.com/5286536/154947901-e65eff59-757c-466b-a921-59326eb762ce.png">

But when I click on one (like airflow), I receive

<img width="1652" alt="kubeapps_airflow" src="https://user-images.githubusercontent.com/5286536/154948030-b92e8ff2-d776-484c-b08f-c2744f19ceba.png">

Do you know how to fix that?

**Comment by absoludity** [comment, marked as answer]
~~Thanks @junoriosity , though I meant if you could create an issue, not a discussion (they're two different things on Github), since this one is actually an issue. I've created #4323 .~~

So after investigating, I found the problem: for historical reasons, by default Kubeapps determines which cluster in the config is the one on which Kubeapps is installed (and hence, the one where global package repositories are present), by checking for a cluster *without* an `APIServiceURL`. This is because, prior to using pinniped's impersonation proxy, this was always true. But when a setup requires pinniped's impersonation proxy, we end up setting the `APIServiceURL` for each cluster and so Kubeapps has no way to know which cluster is the one with the global package repositories.

For this reason, we introduced an extra field in the clusters config, `isKubeappsCluster`, to be able to identify unambiguously which cluster is the one on which Kubeapps is installed (if any - yes, there are situations where you may not target that cluster at all).

So the solution here is to set the [`isKubeappsCluster` in your clusters config, as documented in the values.yaml](https://github.com/kubeapps/kubeapps/blob/v2.4.3/chart/kubeapps/values.yaml#L1503-L1505).

**Reply by junoriosity** [reply]
Many thanks for your immediate reply. I used to set now

```
clusters:
  - apiServiceURL: https://... # impersonation proxy URL
    certificateAuthorityData: ... #  impersonation proxy CA
    isKubeappsCluster: true
    name: default
    pinnipedConfig:
      enabled: true
```

yet the error from above remains.
