### DISCUSSION TITLE
Kubeapps in k8s with OAuth2 proxy: fail to login in (blank page)

### DISCUSSION THREAD

**Discussion by Nibelheims** [kubeapps/kubeapps#4339] [Q&A] [answered]
Hello,

First of all thank you for the Kubeapps tool.
I have used it for a POC in a kubernetes cluster and it worked well. That first instance relied on a token to work.

I now want to move from that kind of devel setup to something more production ready. I now work with a k8s cluster which uses keycloak and OAuth2 proxy. SSO works well to log into services or apps such as a dummy dokuwiki for testing purposes. kubelogin also works well.

I have tried to follow the following docs:
- https://kubeapps.com/docs/access-control/
- https://kubeapps.com/docs/using-an-OIDC-provider/
- https://oauth2-proxy.github.io/oauth2-proxy/docs/configuration/oauth_provider/#keycloak-oidc-auth-provider

I ended up with the following:
- a keycloak client named k8s with a groups claim
- k8s api server configured to use OIDC (with the groups-claim, issuer URL for authenth, and a username-claim)
- kubeapps 2.4.2 deployed with the following values:
```
        authProxy:
          enabled: true
          external: true
          skipKubeappsLoginPage: false
          provider: oidc
          clientID: k8s
          scope: "groups"
          oauthLoginURI: https://auth.<DOMAIN>/oauth2/start?rd=https://kubeapps.<DOMAIN>/oauth2/callback
          additionalFlags: [--oidc-issuer-url=https://iam.<DOMAIN>/auth/realms/k8s]
        postgresql:
          postgresqlPassword: xxxx
          persistence:
            enabled: true
```
- ingress rule to kubeapps (w/o OAuth2 annotations, this is a "direct" route to kubeapps)
- a keycloak group with proper (hope so) RBAC config on k8s side (no specific assigned role on keycloak's side) ; RBAC are defined with the --group flag, and the name of that group
- a keycloak user which belongs to that group

When I try to log into kubeapps, the following happens:
1. I first clean every cookie in my browser, just in case
2. I open the kubeapps' URL in my browser
3. Kubeapps' login page shows up, with a button "OIDC login"
4. I click that button
5. A keycloak auth form shows up, I fill in the credentials of the dedicated user
6. The credentials are accepted, and I get redirected to the kubeapps/oauth2/callback page, which *is blank, nothing happens*

I'm stuck there currently. Do you have any idea of what could be wrong? That kind of environment can become complex, I hope I have provided enough information.

Thanks and best regards
