### DISCUSSION TITLE
Authorization

### DISCUSSION THREAD

**Discussion by Wouter053** [kubeapps/kubeapps#4746] [Q&A] [answered]
Hi,

In Kubernetes 1.24 tokens are not created for service accounts. So the authorization procedure in the documentation no longer works:

```
To create a Service Account for a user "example" in the "default" namespace, run the following:
kubectl create -n default serviceaccount example
To get the API token for this Service Account, run the following:
kubectl get -n default secret $(kubectl get -n default serviceaccount example -o jsonpath='{.secrets[].name}') -o go-template='{{.data.token | base64decode}}' && echo
```

So I created service account "example" like above, and then created a token with  
`kubectl create -f token.yml`

token.yml:
```
apiVersion: v1
kind: Secret`
metadata:`
   namespace: default` 
   name: example-secret`
   annotations:`
       kubernetes.io/service-account.name: "example"`
type: kubernetes.io/service-account-token`
```
I then apply this yaml:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: admin-user-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
- kind: ServiceAccount
  name: example
  namespace: default
```

I can now see the token with
`kubectl describe secret example-secret`

However, this token does not get me into the kubeapps dashboard.  It does get me into the standard kubernetes dasboard

Any ideas?
