### DISCUSSION TITLE
patch DNS from kubeapps

### DISCUSSION THREAD

**Discussion by vijimgowda** [kubeapps/kubeapps#4864] [Ideas]
Hi  greetings 

is it possible patch DNS from kubeapps for deployed tools/application  without upgrading  to any next version 

for example in a cloud ,  i have installed jenkins  with ingress ELB.. later i will get domain ( SSL applied domain ) is it possible patch new domain DNS from kubeapps  ??

please confirm me

**Comment by antgamdia** [comment]
Hi,

if I'm getting your point here, in Helm you can always update the values of the deployed version without, necessarily, bumping up the Kubeapps version.

For instance:

Assuming you deploy Kubeapps with the default values (ie. `helm upgrade --install -n kubeapps --create-namespace kubeapps bitnami/kubeapps`), you can always create your `my-values.yaml` file (below is an example on how to use an ingress-controller) and run:
`helm upgrade --install -n kubeapps --create-namespace kubeapps bitnami/kubeapps --values  my-values.yaml`: 

If you need to stick to a specific version, I'd say adding the `--version x.x.x`  flag will work.


````
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  enabled: true
  hostname: localhost
````
