### ISSUE TITLE
Use PathPrefix on Traefik

### ISSUE THREAD

**Issue by VincentSurelle** [kubeapps/kubeapps#1005]
Hi,

I'm trying to deploy Kubeapps behind Traefik proxy.

I saw many solutions using a subdomain like kubeapps.example.com, but I'm trying to make it work as example.com/catalog.

For this, i'm using Traefik ingress with PathPrefix(Strip) solution

Here is my values.yml

```yaml
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.ingress.kubernetes.io/rule-type: PathPrefix
    traefik.ingress.kubernetes.io/auth-type: "basic"
    traefik.ingress.kubernetes.io/auth-secret: "auth-http"
  hosts:
  - name: mykube.example.com
    path: /catalog
```

With the PathPrefixStrip way, It's all blank since js & css files doesn't use the prefix `/catalog`

But with the PathPrefix way, I can see the UI, I'm being redirected to `/login` but can't see any content. Apparently there's a HEAD request triggered on `/` that returns a 404. Because it doesn't take the prefix.

![Capture d’écran 2019-04-11 à 08 52 51](https://user-images.githubusercontent.com/1504027/55936768-87a1df00-5c37-11e9-9fd7-a3ab3c841cb6.png)

Is there a way to fix it ?

Thanks

**Comment by prydonius** [comment]
Hey @VincentSurelle, sorry for the late response, a few of us have been travelling and on holiday.

I don't really have much experience with Traefik, but PathPrefix should work assuming this preserves the prefix when passing it to the Kubeapps nginx Pods. The rewrites configured for the dashboard nginx Pod should handle a path correctly: https://github.com/kubeapps/kubeapps/blob/52eb0a66988d3c5b711e0024a88c18a29ab67ca9/chart/kubeapps/templates/dashboard-config.yaml#L23-L35. You could take a look at the logs of that Pod to see if something strange is going on there?

**Comment by micafer** [comment]
I have the same issue using a nginx ingress controller.
I do not enable ingress in the chart (as I don't want to set a host name) and I create this ingress YAML manually:

```yaml
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kubeapps
  name: kubeapps
  annotations:
      kubernetes.io/ingress.class: nginx
      nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
spec:
  rules:
    - http:
        paths:
        - backend:
            serviceName: kubeapps
            servicePort: 80
          path: /kubeapps
```

As @VincentSurelle I can see the UI, I'm being redirected to /login but no login form is shown. 
I see the same behaviour: It seems that there's a HEAD request triggered on / that returns a 404. 
My chrome sais that the error is raised in file xhr.js (line 178). 

Furthermore if I change the path to "/" I can see the login and access the application. Then I change the path in the ingress rule to "/kubepass" and I can access this path and access the application (as no login is required).

I'm using version 1.3.2 of kubeapps.
