### ISSUE TITLE
Add ImagePullSecrets for apprepo-sync cronjob

### ISSUE THREAD

**Issue by onesolpark** [kubeapps/kubeapps#188]
I am using a private repository for the repo-sync image.

The problem is ImagePullSecrets isn't included in the cron job that apprepository controller creates.

Currently I am manually editing the cronjob so that the sync that occurs every hour doesn't fail.

Please add imagepullsecrets in to the cronjob to support private registry users like me.

**Comment by prydonius** [comment]
Hi @onesolpark,

You're best solution to this is to add the imagePullSecrets to the default ServiceAccount in the `kubeapps` namespace. That will ensure any pods running in the namespace with the default ServiceAccount will automatically use those imagePullSecrets.

See https://kubernetes.io/docs/tasks/configure-pod-container/configure-service-account/#add-imagepullsecrets-to-a-service-account for more info.

**Comment by prydonius** [comment]
@onesolpark does the above work for you?

**Comment by arapulido** [comment]
Closing for now. @onesolpark please, reopen if the above doesn't fix your issue

**Comment by rredkovich** [comment]
Hi! Seems that I managed to got the issue with configuration for k8s cluster v1.10.11

`imagePullSecret` is set in a cronjob spec, but when job is starting container pull fails:
```bash
  Warning  Failed  3m (x2005 over 7h)  kubelet, ip-172-xxx.internal  Error: ImagePullBackOff
```

Tried to set `imagePullSecrets` to the default `ServiceAccount`, still doesn't work.

Here is the cronjob config:
```yaml
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: elastic-clean
  namespace: infrastructure
spec:
  # https://crontab.guru/#50_23_*_*_*
  schedule: "50 23 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: elastic-clean
        spec:
          imagePullSecrets:
            - name: the-secret-name
          containers:
          - name: elastic-clean
            image: our-organisation/image:version_tag
            imagePullPolicy: IfNotPresent
            env:
              - name: ELASTICSEARCH_URL
                value: "locationofhost"

          restartPolicy: OnFailure
```

Default service account config:
```yaml
➜  ~ kubectl get serviceaccounts default -o yaml
apiVersion: v1
imagePullSecrets:
- name: the-secret-name
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-09-06T11:50:20Z
  ...
secrets:
- name: default-token-xxxx
```

Deployments in same namespace works correctly with `imagePullSecrets`.
