### ISSUE TITLE
[FEATURE REQUEST] crontab per repository

### ISSUE THREAD

**Issue by kfirfer** [kubeapps/kubeapps#2057]
Hello

would be nice to crontab per repository
In the chart, for example:
```
apprepository:
  initialRepos:
    - name: bitnami
      url: https://charts.bitnami.com/bitnami
      crontab: "*/60 * * * *"
```

And in the UI
