### ISSUE TITLE
Can't login to kubeapps using Keycloak

### ISSUE THREAD

**Issue by kvaps** [kubeapps/kubeapps#2111]
### Description:

Can't login to kubeapps using Keycloak, kubeapps proxies requests as `system:anonymous` user.

### Steps to reproduce the issue:

1. Oauth2_proxy configured like this:

```yaml
authProxy:
  enabled: true
  provider: "keycloak"
  clientID: "kubeapps"
  clientSecret: "<redacted>"
  cookieSecret: "<redacted>"
  emailDomain: "*"
  additionalFlags:
    - --oidc-issuer-url=https://auth.kc.stage.example.org/realms/example
    - --login-url=https://auth.kc.stage.example.org/realms/example/protocol/openid-connect/auth
    - --redeem-url=https://auth.kc.stage.example.org/realms/example/protocol/openid-connect/token
    - --validate-url=https://auth.kc.stage.example.org/realms/example/protocol/openid-connect/userinfo
    - --keycloak-group=kubeapps
    - --user-id-claim=email
    - --ssl-insecure-skip-verify
    - --cookie-secure=false
```

2. User has cluster-admin privileges

3. kubectl works fine

4. Login to the kubeapps redirects to the main login page

### Describe the results you received:

I see that login is succeed but `/api/clusters/default/` returns:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

### Describe the results you expected:

Successful login to the dashboard

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.3", GitCommit:"", GitTreeState:"", GoVersion:"go1.15"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
NAME    	NAMESPACE	REVISION	UPDATED                                 	STATUS  	CHART         	APP VERSION  
kubeapps	kubeapps 	20      	2020-10-13 18:07:45.217658758 +0200 CEST	deployed	kubeapps-4.0.3	v2.0.0-beta.2
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:30:33Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by batiati** [comment]
Hi,

I'm facing kind of same issue here. I thought that I was doing something wrong (see #1874), but it seems that there is something tricky on that matter. 

If it is not a bug, certainly it's an opportunity to improve the docs.

**Comment by andresmgot** [comment]
What are the logs of Keycloak and the kube-apiserver  pod? That should show more information about the error.

**Comment by kvaps** [comment]
auth-proxy log:
```
10.112.1.245:36708 - - [2020/10/14 08:43:25] kubeapps-stage.example.org GET - "/oauth2/start" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0" 302 318 0.000
10.112.1.245:36708 - - [2020/10/14 08:43:27] kubeapps-stage.example.org GET - "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0" 403 2642 0.000
```

keycloak log:
```
{
  "@timestamp": "2020-10-14T08:43:26.163Z",
  "sequence": 2577,
  "loggerClassName": "org.jboss.logging.Logger",
  "loggerName": "org.keycloak.events",
  "level": "INFO",
  "message": "type=CODE_TO_TOKEN, realmId=nextcloud, clientId=kubeapps, userId=1cdd3e59-a195-4f61-957f-8e737179b3eb, ipAddress=10.28.36.177, token_id=8841e94a-d49c-4490-835d-445e62d7007b, grant_type=authorization_code, refresh_token_type=Refresh, scope='openid email profile', refresh_token_id=d3e2bb31-79be-4cdb-b8f1-2e88d3675780, code_id=b931940d-2bed-408d-ab08-a35cce7c3524, client_auth_method=client-secret",
  "threadName": "default task-13",
  "threadId": 10659,
  "mdc": {},
  "ndc": "",
  "hostName": "keycloak-1",
  "processName": "jboss-modules.jar",
  "processId": 508,
  "@version": "1"
}
```

apisrver logs are clean

<s>I use kubeapps behind the nginx-ingress-controller, not sure if it is connected.</s> - it's don't, port-forward is not working as well

**Comment by andresmgot** [comment]
okay, so that was not that helpful. Some more questions that may help debugging the issue.
 - How have you configured the cluster to use Keycloak as OIDC provider?
 - Are you able to use `kubectl` with the token that the proxy uses? You can retrieve it from the `Authorization` header in the `Network` tab of your browser.
 - Are there any error logs in the Ingress controller?

**Comment by kvaps** [comment]
@andresmgot oauth2-proxy does not set any `Authorization` on the browser.
I have only `_oauth2_proxy` cookie set with some value, but it can't be easily decrypted *(see: https://github.com/oauth2-proxy/oauth2-proxy/issues/623)*

Otherwise, I see that `POST` request to my keycloak is stting the next cookies, with the following payload *(decrypted using [jwt.io](https://jwt.io/))*:

```yaml
KC_RESTART (in request cookies):
  {
    "cid": "kubeapps",
    "pty": "openid-connect",
    "ruri": "http://kubeapps-stage.example.org/oauth2/callback",
    "act": "AUTHENTICATE",
    "notes": {
      "scope": "openid email groups",
      "iss": "https://auth.kc.stage.example.org/realms/example",
      "response_type": "code",
      "client_request_param_approval_prompt": "force",
      "redirect_uri": "http://kubeapps-stage.example.org/oauth2/callback",
      "state": "6aa8b4017db17234aee160ba1adf63f2:/"
    }
  }
KEYCLOAK_IDENTITY (in response cookies):
  {
    "jti": "482233f9-2a4d-4091-adc9-a6138d2fd4cc",
    "exp": 1602722745,
    "nbf": 0,
    "iat": 1602686745,
    "iss": "https://auth.kc.stage.example.org/realms/example",
    "sub": "1cdd3e59-a195-4f61-957f-8e737179b3eb",
    "typ": "Serialized-ID",
    "auth_time": 0,
    "session_state": "658f99e6-4901-4b35-bc23-eb74b795b708",
    "state_checker": "0fJlvg0GJHPNYalQCkuFEVTX0ryw42tfI8A3FcGcphA"
  }
```

https://auth.nc.stage.example.org/realms/example/login-actions/authenticate?session_code=HDmWlTvRlZ96xlJpQGu1p80SV36P9NfTWxJU1gNUay4&execution=a33adc5c-4646-4250-9b43-f060ae45d872&client_id=kubeapps&tab_id=-oEN6b4bbhY

**Comment by kvaps** [comment]
looks like related https://github.com/bitly/oauth2_proxy/issues/530

I've tried to set:
```yaml
    - --pass-authorization-header=true
    - --set-authorization-header=true
```
unfortunately it didn't help

**Comment by kvaps** [comment]
After specifying these two flags I've got bearer token in the `X-Auth-Request-Access-Token` response header, however If I try to use it via kubectl my apiserver shows the following error:

```
E1014 15:26:20.133433       1 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token
```

**Comment by batiati** [comment]
* ### How have you configured the cluster to use Keycloak as OIDC provider?

I have used the keycloak operator to install keycloak and create the realm, and then I've tried to created a RoleBinding to my group, user and email.
Is there something else needed?? I did most the setup following keycloak's operator guide.

```
kubectl create clusterrolebinding kubeapps-cluster-admin --clusterrole=cluster-admin --group /kubeapps --user batiati --user batiati@triadesolucoes.com.br
```


* ###  Are you able to use `kubectl` with the token that the proxy uses? You can retrieve it from the `Authorization` header in the `Network` tab of your browser.

There is no `Authorization` header on Request, just the `_oauth2_proxy` cookie

![image](https://user-images.githubusercontent.com/5728002/96011890-e5f5e200-0e19-11eb-9b46-55b59a59f8b8.png)

* ###  Are there any error logs in the Ingress controller?

Kubeapps nginx pod:
```
127.0.0.1 - - [14/Oct/2020:15:51:15 +0000] "GET /api/clusters/default/ HTTP/1.1" 401 165 "https://kubeapps.multiclubes.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36"
```

Kubeapps oauth-proxy pod:
```
10.42.0.0:33470 - batiati@triadesolucoes.com.br [2020/10/14 15:50:02] [AuthSuccess] Authenticated via OAuth2: Session{email:batiati@triadesolucoes.com.br user:24785368-d4d5-4b70-980f-730d3727576c PreferredUsername:batiati token:true id_token:true created:2020-10-14 15:50:02.644119279 +0000 UTC m=+52.842325435 expires:2020-10-14 15:51:02.643638777 +0000 UTC m=+112.841844833 refresh_token:true}
10.42.0.0:33470 - - [2020/10/14 15:50:02] kubeapps.multiclubes.com.br GET - "/oauth2/callback?state=7fbc053b9472a06baa30e9e8ec8ba852%3A%2F&session_state=54b44622-f235-437f-b368-32fa78e0502a&code=372e3c04-f65b-4b5a-aaa3-f3ef6a6b27c5.54b44622-f235-437f-b368-32fa78e0502a.fdf564b3-5594-4570-b0f0-c40dec9902bb" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 302 24 0.024
10.42.0.0:33470 - - [2020/10/14 15:50:02] kubeapps.multiclubes.com.br GET / "/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 304 0 0.001
10.42.0.0:33470 - batiati@triadesolucoes.com.br [2020/10/14 15:50:03] kubeapps.multiclubes.com.br GET / "/api/clusters/default/" HTTP/1.1 "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 401 165 0.003
```


K8s nginx ingress
```
172.30.2.46 - - [14/Oct/2020:15:45:34 +0000] "GET /oauth2/start HTTP/2.0" 302 331 "https://kubeapps.multiclubes.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 178 0.001 [kubeapps-kubeapps-3000] [] 10.42.1.98:3000 331 0.002 302 571dba0da137b1b8910d1cd8f8ddb4ae
172.30.2.46 - - [14/Oct/2020:15:45:34 +0000] "GET /auth/realms/master/protocol/openid-connect/auth?approval_prompt=force&client_id=kubeapps&redirect_uri=http%3A%2F%2Fkubeapps.multiclubes.com.br%2Foauth2%2Fcallback&response_type=code&scope=openid+email+groups&state=b150f768da66c8e6fe22db5c9c00038b%3A%2F HTTP/2.0" 302 0 "https://kubeapps.multiclubes.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 1470 0.022 [keycloak-keycloak-http-http] [] 10.42.1.95:8080 0 0.021 302 e50fe61f3a49e61f7e42dd6ae66f780b
172.30.3.107 - - [14/Oct/2020:15:45:34 +0000] "POST /auth/realms/master/protocol/openid-connect/token HTTP/1.1" 200 1969 "-" "Go-http-client/1.1" 516 0.018 [keycloak-keycloak-http-http] [] 10.42.1.95:8080 3224 0.019 200 8a769cfaabb5e3f7b119d476d5a944bd
172.30.3.107 - - [14/Oct/2020:15:45:34 +0000] "GET /auth/realms/master/protocol/openid-connect/userinfo HTTP/1.1" 200 232 "-" "Go-http-client/1.1" 1348 0.004 [keycloak-keycloak-http-http] [] 10.42.1.95:8080 232 0.005 200 0b42019a9b9c0c035da87b2d94d288dc
172.30.2.46 - - [14/Oct/2020:15:45:34 +0000] "GET /oauth2/callback?state=b150f768da66c8e6fe22db5c9c00038b%3A%2F&session_state=302b9c0f-0517-4d34-9599-cb8958f272fa&code=b362173a-13c3-46c6-84a3-4cd1250972a2.302b9c0f-0517-4d34-9599-cb8958f272fa.fdf564b3-5594-4570-b0f0-c40dec9902bb HTTP/2.0" 302 24 "-" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 1724 0.025 [kubeapps-kubeapps-3000] [] 10.42.1.98:3000 24 0.026 302 31e6c4cfbcef749cd272351ebe197d34
172.30.2.46 - - [14/Oct/2020:15:45:34 +0000] "GET /api/clusters/default/ HTTP/2.0" 401 165 "https://kubeapps.multiclubes.com.br/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/86.0.4240.75 Safari/537.36" 1497 0.003 [kubeapps-kubeapps-3000] [] 10.42.1.98:3000 165 0.004 401 0a35a60dfe4d5db6e5307788e9698565
```

**Comment by kvaps** [comment]
Hm, it seems this token was really broken, new one displays nothing even if apiserver running with `-v 10`.

I just compared payload of two tokens, first which I've got from oauth2-proxy, the second which I got from kubelogin (the working one):

```diff
--- kubeapps
+++ kubelogin
@@ -1,44 +1,17 @@
 {
-  "jti": "2c6c0e12-c2f3-44c6-acd2-42d032062105",
-  "exp": 1602691152,
+  "jti": "77d9f41d-3f29-4657-a3ce-4feddfbab006",
+  "exp": 1602691125,
   "nbf": 0,
-  "iat": 1602690852,
+  "iat": 1602690825,
   "iss": "https://auth.kc.stage.example.org/realms/example",
-  "aud": [
-    "Someapp",
-    "account"
-  ],
+  "aud": "kubeapps",
   "sub": "1cdd3e59-a195-4f61-957f-8e737179b3eb",
-  "typ": "Bearer",
+  "typ": "ID",
   "azp": "kubeapps",
-  "auth_time": 1602690852,
-  "session_state": "34d4da0d-6a0e-4fe2-87a9-7ad8bb92c947",
-  "acr": "1",
-  "allowed-origins": [
-    "https://kubeapps-stage.example.org"
-  ],
-  "realm_access": {
-    "roles": [
-      "offline_access",
-      "uma_authorization"
-    ]
-  },
-  "resource_access": {
-    "Someapp": {
-      "roles": [
-        "admin",
-        "onlyoffice"
-      ]
-    },
-    "account": {
-      "roles": [
-        "manage-account",
-        "manage-account-links",
-        "view-profile"
-      ]
-    }
-  },
-  "scope": "openid email profile",
+  "nonce": "Xzd3fBXD1YuM4z1gUeWagkowCpqjTXzXAFq0zLMYjUg",
+  "auth_time": 1602684626,
+  "session_state": "2a533390-db98-4b34-a684-69ebb1b25fb5",
+  "acr": "0",
   "name": "Andrei Kvapil Kvapil",
   "groups": [
     "elk-admins",
```

**Comment by batiati** [comment]
> After specifying these two flags I've got bearer token in the `X-Auth-Request-Access-Token` response header, however If I try to use it via kubectl my apiserver shows the following error:
> 
> ```
> E1014 15:26:20.133433       1 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token
> ```

After specifying `- --set-authorization-header=true` on oauth-proxy, the `authorization` header was rendered.
But same error if I try to use it on kubectl

![image](https://user-images.githubusercontent.com/5728002/96014991-68cc6c00-0e1d-11eb-9915-62c839cb3b6b.png)

**Comment by andresmgot** [comment]
okay, so this seems indeed two different issues.

@batiati I believe that the error (at least the first one to deal with) is that you need to configure your Kubernetes API to trust Keycloak and be able to authenticate yourself using OIDC. The steps to do so will vary depending on your cluster provider. For example, in our dev environment with `kind` (Kubernetes in Docker) we set extra parameters for configuring the cluster here: https://github.com/kubeapps/kubeapps/blob/master/docs/user/manifests/kubeapps-local-dev-apiserver-config.yaml#L15

@kvaps your oauth2_proxy token seems fine, I am not sure where the issue can be in your case. I am surprised none of the logs says anything relevant about the issue. If the token that oauth2_proxy generates is not valid, it means that either keycloak or oauth2_proxy requires extra configuration. Can you share the steps you have followed for creating the cluster and configure everything so I can try to reproduce the issue?

**Comment by kvaps** [comment]
@andresmgot just tried another keycloak, result kubeapps is not working, but kubectl (original issued by [kuberos](https://github.com/negz/kuberos)) working fine:

```diff
--- /tmp/kubeapps
+++ /tmp/kubectl
@@ -1,35 +1,16 @@
 {
-  "jti": "43ba64bd-6e56-4a57-8775-e50a790a919e",
-  "exp": 1602764087,
+  "jti": "af3ae96a-fcc3-4b1b-8d93-544e239f0fa9",
+  "exp": 1602763655,
   "nbf": 0,
-  "iat": 1602763787,
+  "iat": 1602763355,
   "iss": "https://keycloak.example.org/auth/realms/kubernetes",
   "aud": "kubernetes",
   "sub": "337a5e4b-ecce-4ef6-b28e-d89220ec0830",
-  "typ": "Bearer",
+  "typ": "ID",
   "azp": "kubernetes",
-  "auth_time": 1602763787,
-  "session_state": "d98b51f9-4525-4ac9-ac23-c39588afb12b",
+  "auth_time": 1597855430,
+  "session_state": "cf811661-2a3a-4400-8ac0-03fe578c6aad",
   "acr": "1",
-  "allowed-origins": [
-    "https://kubernetes.example.org"
-  ],
-  "realm_access": {
-    "roles": [
-      "offline_access",
-      "uma_authorization"
-    ]
-  },
-  "resource_access": {
-    "account": {
-      "roles": [
-        "manage-account",
-        "manage-account-links",
-        "view-profile"
-      ]
-    }
-  },
-  "scope": "openid profile email groups",
   "name": "Andrei Kvapil",
   "groups": [
     "rocketchat-users",
```

Can't it be connected with the fact that Kubernetes requires ID token, but oauth2-proxy provides the Bearer one?

> Can you share the steps you have followed for creating the cluster and configure everything so I can try to reproduce the issue?

Sure here is an article how to configure Keycloak, which describes exact my configuration:
https://medium.com/@kvaps/adding-ldap-authentication-to-kubernetes-5c1f894a5a98

My current values.yaml:
```yaml
allowNamespaceDiscovery: true
ingress:
  enabled: true
  hostname: kubeapps-stage.example.org
  annotations:
    kubernetes.io/ingress.class: nginx-internal
authProxy:
  enabled: true
  provider: "keycloak"
  clientID: "kubernetes"
  clientSecret: "df873656-be02-491a-99cd-e6352e55fb9d"
  cookieSecret: "hdw771o2sN18pGAsWDGMjg=="
  emailDomain: "*"
  additionalFlags:
    - --oidc-issuer-url=https://keycloak.example.org/auth/realms/kubernetes
    - --login-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/auth
    - --redeem-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/token
    - --validate-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/userinfo
    - --user-id-claim=email
    - --ssl-insecure-skip-verify
    - --cookie-secure=false
    - --pass-authorization-header=true
    - --set-authorization-header=true
    - --set-xauthrequest
```

**Comment by kvaps** [comment]
Hi, I just tried to replace oauth2-proxy by [louketo-proxy](https://github.com/louketo/louketo-proxy) (formerly known as keycloak-gatekeeper) and found that it is working fine in this configuration, see the PR https://github.com/kubeapps/kubeapps/pull/2115

**Comment by andresmgot** [comment]
> Can't it be connected with the fact that Kubernetes requires ID token, but oauth2-proxy provides the Bearer one?
> 

As far as I can remember we have found that issue in the past and we were able to make it work with oauth2_proxy. @absoludity may know more about this.

> Sure, here is an article how to configure Keycloak for Kubernetes, it describes exact my configuration:
> https://medium.com/@kvaps/adding-ldap-authentication-to-kubernetes-5c1f894a5a98

Thanks, that will be helpful to reproduce the issue.

> Hi, I just tried to replace oauth2-proxy by [louketo-proxy](https://github.com/louketo/louketo-proxy) (formerly known as keycloak-gatekeeper) and found that it is working fine with the Keycloak in this configuration, see the PR #2115

Thanks for the PR, in the past we were using keycloak-gatekeeper but we decided to move away from it for compatibility with different platforms. See more info here: https://github.com/kubeapps/kubeapps/pull/1199

There should be a way to configure Keycloak-oauth2_proxy to work together, we probably need to spend more time investigating this.

**Comment by absoludity** [comment]
> Can't it be connected with the fact that Kubernetes requires ID token, but oauth2-proxy provides the Bearer one?

Hi @kvaps . I think you're referring to the `typ` field in your diff above, but afaict, those diffs are of the [Keycloak Requesting Party Token (RPT)](https://www.keycloak.org/docs/4.8/authorization_services/#_service_rpt_overview), so it's not clear how that relates to the actual ID token which is being used (and failing for you with oauth2-proxy). 

The important thing to remember here (probably obvious, but just stating) is that neither oauth2-proxy nor louketo-proxy are creating the ID tokens - they just request them from the identity provider (Keycloak, in this case), the IdP creates and signs them and sends them back to the proxy (with other data). So the difference will be with how oauth2-proxy is configured to request the token (how that differs from what louketo requests).

As was mentioned, the best thing to do is run with `--set-authorization-header=true` as you appear to be and grab the token which oauth2-proxy is using from the response (see batiati's example above). You mentioned that you don't see any authorization bearer header - which will be true without that setting, so I can only guess that was before you updated to use `--set-authorization-header=true` *or* oauth2-proxy is never getting an ID token from Keycloak (but the logs for oauth2-proxy which you pasted above contradict that)? Otherwise I'm confused why you're not seeing it in your client browser when using the `--set-authorization-header=true`.

> After specifying these two flags I've got bearer token in the `X-Auth-Request-Access-Token` response header, 

I don't think that's an ID token but the *access* token, which means that:

>however If I try to use it via kubectl my apiserver shows the following error:
> 
> ```
> E1014 15:26:20.133433       1 authentication.go:53] Unable to authenticate the request due to an error: invalid bearer token
> ```

Correct, as your api server requires an id_token as the Bearer, not an access token.

Anyway, based on the [sunsetting of the louketo project](https://github.com/louketo/louketo-proxy/issues/683), it sounds like they'll have a migration guide (or may already) which will help us here.

As Andres mentioned, we need to reproduce and investigate, as oauth2-proxy should work with any IDP. I'll try and do that soon.

**Comment by kvaps** [comment]
Okay I made some investigation, and it seems found the bug:

problem is that kubernetes expecting `Authorization: Bearer` header but oauth2-proxy not passing it even if `--pass-authorization-header` option set

**Comment by kvaps** [comment]
Probably related issue https://github.com/oauth2-proxy/oauth2-proxy/issues/843

**Comment by absoludity** [comment]
> Probably related issue [oauth2-proxy/oauth2-proxy#843](https://github.com/oauth2-proxy/oauth2-proxy/issues/843)

I don't think so, that bug (843) is about having oauth2-proxy forward the oauth2 *access* token upstream, rather than the *id_token* which it always does by default. We actually enable using the access token rather than the id token  in a specific case, gke, with a `frontend.proxypassAccessTokenAsBearer=true` option as documented in [example 3 in the docs](https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md#using-the-chart), by [overwriting the `Authorization: Bearer` header](https://github.com/kubeapps/kubeapps/blob/master/chart/kubeapps/templates/kubeapps-frontend-config.yaml#L21).



> Okay I made some investigation, and it seems found the bug:
> 
> problem is that kubernetes expecting `Authorization: Bearer` header but oauth2-proxy not passing it even if `--pass-authorization-header` option set
> 
> Thanks to https://hub.docker.com/r/containous/whoami image which allowed me to debug the headers

I'm using oauth2-proxy and it definitely sets the `Authorization: Bearer` with the `id_token` by default. This is the [behaviour of oauth2-proxy](https://oauth2-proxy.github.io/oauth2-proxy/#behavior) and how it works. So if you are seeing a request come through to the k8s api server *without* the `Authorization: Bearer` header, possibilities I can think of are:

* I'm mistaken in some way :P

**Comment by kvaps** [comment]
> I'm using oauth2-proxy and it definitely sets the Authorization: Bearer with the id_token when configured with kubeapps (we set the --pass-authorization-header=true option).

So do you have `"typ": "Bearer"` or `"typ": "ID"`for your tokens issued by oauth2-ptroxy?

Because I have `"typ": "Bearer"` tokens and this is not working correct with oauth2-proxy, it is setting `X-Forwarded-Access-Token` but not `X-Auth-Token`, `Authorization: Bearer`, while louketo-proxy doing that for `"typ": "Bearer"`.

Meanwhile kubectl is requesting `"typ": "ID"` tokens, not `"typ": "Bearer"`

**Comment by kvaps** [comment]
Just copypaste from [here](https://github.com/oauth2-proxy/oauth2-proxy/issues/843#issuecomment-717212451):

oauth2-proxy is running as a sidecar and proxying the requests to the application itself:

```yaml
      - args:
        - --provider=keycloak
        - --client-id=kubernetes
        - --client-secret=7b412da4-548a-44af-a2c1-6b42a5c46431
        - --cookie-secret=x-1vrrMhC-886ITuz8ySNw==
        - --upstream=http://localhost:8080/
        - --http-address=0.0.0.0:3000
        - --email-domain=*
        - --pass-basic-auth=false
        - --pass-access-token=true
        - --set-xauthrequest=true
        - --skip-jwt-bearer-tokens=true
        - --set-authorization-header=true
        - --pass-authorization-header=true
        - --skip-auth-regex=^\/config\.json$
        - --skip-auth-regex=^\/favicon.*\.png$
        - --skip-auth-regex=^\/static\/
        - --skip-auth-regex=^\/$
        - --scope=openid email groups
        - --oidc-issuer-url=https://keycloak.example.org/auth/realms/kubernetes
        - --login-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/auth
        - --redeem-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/token
        - --validate-url=https://keycloak.example.org/auth/realms/kubernetes/protocol/openid-connect/userinfo
        - --keycloak-group=ipausers
```

But after the successful authentication my application see only these headers:

```yaml
Hostname: kubeapps-84f7f5f7f6-v4hq4
IP: 127.0.0.1
IP: ::1
IP: 10.112.2.173
IP: fd00::2:f2c0
IP: fe80::8ce:b4ff:fe9e:10e7
RemoteAddr: [::1]:47192
GET /a HTTP/1.1
Host: kubeapps-stage.example.org
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip, deflate, br
Accept-Language: ru,en-US;q=0.7,en;q=0.3
Cache-Control: max-age=0
Cookie: < my cookies here >
Dnt: 1
Upgrade-Insecure-Requests: 1
X-Forwarded-Access-Token: < Bearer token here >
X-Forwarded-Email: andrei.kvapil@example.org
X-Forwarded-For: 10.31.2.82, 10.112.1.245
X-Forwarded-Host: kubeapps-stage.example.org
X-Forwarded-Port: 443
X-Forwarded-Proto: https
X-Real-Ip: 10.31.2.82
X-Request-Id: 40aa3757f3387296d30fcad6b8a0b089
X-Scheme: https
```

However if I use louketo-proxy:

```yaml
      - args:
        - --discovery-url=https://keycloak.example.org/auth/realms/kubernetes
        - --client-id=kubernetes
        - --client-secret=7b412da4-548a-44af-a2c1-6b42a5c46431
        - --encryption-key=oowuPaquoxe5ephaehah6aeb8ieweesu
        - --upstream-url=http://localhost:8080/
        - --listen=0.0.0.0:3000
        - --resources=uri=/config.json|white-listed=true
        - --resources=uri=/favicon*.png|white-listed=true
        - --resources=uri=/static/*|white-listed=true
        - --scopes=openid+email+groups
        - --enable-session-cookies=true
        - --enable-refresh-tokens=true
        - --enable-logout-redirect
        - --enable-logging=true
        - --verbose=true
```


```yaml
Hostname: kubeapps-654c8b8db4-m2vmf
IP: 127.0.0.1
IP: ::1
IP: 10.112.2.159
IP: fd00::2:7973
IP: fe80::e4:27ff:fe3b:702d
RemoteAddr: [::1]:60838
GET / HTTP/1.1
Host: localhost:8080
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:80.0) Gecko/20100101 Firefox/80.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Accept-Encoding: gzip
Accept-Language: ru,en-US;q=0.7,en;q=0.3
Authorization: Bearer  < Bearer token here >
Cache-Control: max-age=0
Cookie: < My cookie here >
Dnt: 1
Upgrade-Insecure-Requests: 1
X-Auth-Audience: kubernetes
X-Auth-Email: andrei.kvapil@wedos.org
X-Auth-Expiresin: 2020-10-26 22:05:17 +0000 UTC
X-Auth-Groups: < My user groups here>
X-Auth-Roles: offline_access,uma_authorization,account:manage-account,account:manage-account-links,account:view-profile
X-Auth-Subject: 337a5e4b-ecce-4ef6-b28e-d89220ec0830
X-Auth-Token:  < Bearer token here >
X-Auth-Userid: kvaps
X-Auth-Username: kvaps
X-Forwarded-For: 127.0.0.1
X-Forwarded-Host: localhost:8080
X-Forwarded-Proto: 
```

In fact louketo-proxy is working, but with oauth2-proxy I'm getting, when I'm trying to access Kubernetes API:

```json
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {
    
  },
  "status": "Failure",
  "message": "forbidden: User \"system:anonymous\" cannot get path \"/\"",
  "reason": "Forbidden",
  "details": {
    
  },
  "code": 403
}
```

https://github.com/oauth2-proxy/oauth2-proxy/pull/826 does not solves this problem
