### ISSUE TITLE
Running kubeapps on a cluster behind proxy that requires to configure proxy ceriticate

### ISSUE THREAD

**Issue by h-uchida-n** [kubeapps/kubeapps#2139]
I'd like to use kubeapps on k8s cluster behind a proxy and to refer helm repositories on the internnet (lile https://charts.bitnami.com/bitnami).
Regarding the proxy, proxy certificate should be installed/configured to use it.

 how shold we configure kubeapps?

I've tried following configuration, but it didn't work.

* Each cluster nodes has already installed proxy certificate and configured http_proxy environment.
* Proxy configuration on web console was done. (as followings)  
  ```spec:
    containers:
      - env:
          - name: https_proxy
            value: '<proxy url>'
          - name: http_proxy
            value: '<proxy url>'
  ```

**Comment by andresmgot** [comment]
hi @h-uchida-n,

It's not clear to me if  you have modified the AppRepository `syncJobPodTemplate` as explained here:

https://kubeapps.com/docs/private-app-repository/#modifying-the-synchronization-job

If you do so, you will be able to setup the http_proxy and https_proxy env variables:

```
spec:
  containers:
    - env:
        - name: https_proxy
          value: '<proxy url>'
        - name: http_proxy
          value: '<proxy url>'
```

Can you confirm if that works for you?

**Comment by h-uchida-n** [comment]
Hi @andresmgot , thank you for reply.

Previous post was not good to explain my environment, so I'll try again it below:

* Cluster which kubeapps installed is constructed in private LAN.
* All resources (server / container) should comunicate with the internet via a proxy.
* Following steps are required to use the proxy. (example for Ubuntu)
  1. `# cp <ProxyServerCertificate.crt> /usr/share/ca-certificates`  
     <ProxyServerCertificate.crt> are provided by proxy sever.
  2. `# sh -c "echo 'ZscalerRootCertificate.crt' >> /etc/ca-certificates.conf"` add file path to /etc/ca-certificates.conf
  3. `# update-ca-certificates`

So I guess that above steps are required to use kubeapps in my environment.
Is there any way to do it with configuration? (without modify kubeapps container by myself)

----

Tried following steps but it showed error.

1. `$ kubectl apply -f apprepo_bitnami.yaml`

   ```
   apiVersion: kubeapps.com/v1alpha1
   kind: AppRepository
   metadata:
     name: bitnami2
     namespace: catalog-svc
   spec:
     syncJobPodTemplate:
       spec:
         containers:
           - env:
               - name: https_proxy
                 value: '<proxy url>'
               - name: http_proxy
                 value: '<proxy url>'
     url: https://charts.bitnami.com/bitnami/index.yaml
   ```

2. `$ kubectl logs -n catalog-svc apprepo-catalog-svc-sync-bitnami2-59fmg-g6b22`

   ```
   time="2020-11-05T10:42:09Z" level=error msg="error requesting repo index" error="Get https://charts.bitnami.com/bitnami/index.yaml/index.yaml: x509: certificate signed by unknown authority" url="https://charts.bitnami.com/bitnami/index.yaml/index.yaml"
   time="2020-11-05T10:42:09Z" level=fatal msg="Get https://charts.bitnami.com/bitnami/index.yaml/index.yaml: x509: certificate signed by unknown authority"
   ```
