### ISSUE TITLE
How to configure kubeapps to be served behind a reverse proxy subpath

### ISSUE THREAD

**Issue by bsctl** [kubeapps/kubeapps#2152]
## Question:
How to configure kubeapps to be served behind a reverse proxy subpath?
For example, having a main domain https://main.domain, we want to serve it as https://main.domain/kubapps

**Comment by absoludity** [comment]
It should be possible with the nginx-ingress (if you're using that): https://github.com/kubernetes/ingress-nginx/tree/master/docs/examples/rewrite#examples , though we're not testing this setup at the moment. If you're using oauth, you'll need to also set the `authProxy.oauth{Login|Logout}URI`.

**Comment by bsctl** [comment]
@absoludity we used haproxy ingress controller as following:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    haproxy.org/path-rewrite: /catalog/(.*) /\1
  labels:
    app: kubeapps
    app.kubernetes.io/instance: catalog
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: kubeapps
    chart: kubeapps-4.0.4
    helm.sh/chart: kubeapps-4.0.4
    heritage: Helm
    release: catalog
  name: catalog-kubeapps
  namespace:
spec:
  rules:
  - host: console.example.com
    http:
      paths:
      - backend:
          serviceName: catalog-kubeapps
          servicePort: http
        path: /catalog
        pathType: ImplementationSpecific
status:
  loadBalancer: {}
```

Intentions are to serve Kubeapps under https://console.example.com/catalog

It seems to work except for the some assets, i.e chart icons that are not loaded by the browser (404), eg.

`https://console.example.com/api/assetsvc/v1/ns/cmp-system/assets/bitnami/rabbitmq/logo`

Is there any way to make Kubeapps proxy-aware, for example as Grafana does? I mean introduce an option like `serve_from_sub_path: 'true'`

**Comment by antgamdia** [comment]
Hi @bsctl, I've been trying to reproduce your issue, but I'm not able to.

I'm using Kubeapps v2.0.0 (chart version 4.0.4) with a simple local cluster with [Kind](https://kind.sigs.k8s.io/) and a [HAProxy ingress controller](https://haproxy-ingress.github.io/v0.11/docs/getting-started/),  I used your ingress configuration as follows and every logo is being loaded well with this URL pattern: 
`http://console.example.com/catalog/api/assetsvc//v1/ns/kubeapps/assets/bitnami/rabbitmq/logo`

Which Kubeapps version are you running?

```yaml
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: haproxy
    haproxy.org/path-rewrite: /catalog/(.*) /\1
  name: catalog-kubeapps
spec:
  rules:
  - host: console.example.com
    http:
      paths:
      - backend:
          serviceName: kubeapps
          servicePort: 80
        path: /catalog
        pathType: ImplementationSpecific
```
