### ISSUE TITLE
Namespaced initial repos with authorization not working

### ISSUE THREAD

**Issue by latiif** [kubeapps/kubeapps#2233]
### Description:

We added an initial repo for a specific namespace, by having the following in our `values.yaml`:

```YAML
apprepository:
    initialRepos:
    -   name: bitnami
        url: https://charts.bitnami.com/bitnami
    -   name: my-private-repo
        url: https://my-private-repo.com
        authorizationHeader: "Bearer <REDACTED>"
        namespace: my-namespace
``` 

While the `bitnami` repository was successfully created, the app repo `my-private-repo` wasn't. 
We suspect this was due to missing secrets in both kubeapps' namespace and the target namespace i.e. `my-namespace`. 

Namespaced repos (without authorization) work, and global repos with authorization also work. The problem seems to come up we have a namespaced repositories _with_ authorization.

We suspect the culprit piece of code lies in the Helm chart, as this scenario wasn't updated when the namespaced repositories were introduced.

After installing kubeapps with the previous excerpt from `values.yaml`, we get a pod that is stuck in state `CreateContainerConfigError`. Upon running `kubectl describe <>` on said pod we see this error message:
```
Error: secret "my-namespace-apprepo-my-private-repo" not found
```
When we check for secrets in the kubeapps' namespace, we see no such secret indeed:
```
> kubectl get secrets -n kubeapps
NAME                                                          TYPE                                  DATA   AGE
apprepo-my-private-repo-secrets                               Opaque                                1      5m16s
default-token-99n9w                                           kubernetes.io/service-account-token   3      62m
kubeapps-db                                                   Opaque                                2      5m16s
kubeapps-internal-apprepository-controller-token-6g85j        kubernetes.io/service-account-token   3      5m16s
kubeapps-internal-apprepository-job-postupgrade-token-xfp79   kubernetes.io/service-account-token   3      5m16s
kubeapps-internal-kubeops-token-gtp8n                         kubernetes.io/service-account-token   3      5m16s
sh.helm.release.v1.kubeapps.v1                                helm.sh/release.v1                    1      5m16s
```
Additionally a secret should be present in the target namespace i.e. `my-namespace`, but upon inspection there is no such secret either:
```
> kubectl get secret -n my-namespace
NAME                  TYPE                                  DATA   AGE
default-token-r64sg   kubernetes.io/service-account-token   3      8m14s
```

### Steps to reproduce the issue:

1. Install chart with an initial repo that's namespaced and requires authorization.
```bash
helm install kubeapps bitnami/kubeapps --version 5.0.0 --namespace kubeapps --values values.yaml 
```
where `values.yaml` is:
```yaml
apprepository:
    initialRepos:
    -   name: bitnami
        url: https://charts.bitnami.com/bitnami
    -   name: my-private-repo
        url: https://my-private-repo.com
        authorizationHeader: "Bearer <REDACTED>"
        namespace: my-namespace
```

### Describe the results you received:

The private repository doesn't work at all.

### Describe the results you expected:

I expected the namespaced private repository to work.

### Additional information you deem important (e.g. issue happens only occasionally):

It works perfectly fine when manually added afterwards via the GUI.

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.4.1", GitCommit:"c4e74854886b2efe3321e185578e6db9be0a6e29", GitTreeState:"dirty", GoVersion:"go1.15.4"}
```

- Output of `helm list -n <kubeapps-namespace> `:

```
NAME    	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART         	APP VERSION
kubeapps	kubeapps 	1       	2021-01-08 15:10:59.216099396 +0100 CET	deployed	kubeapps-5.0.0	2.0.1      
```

- Output of `kubectl version`:

```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-12T10:37:08Z", GoVersion:"go1.15.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
```
