### ISSUE TITLE
chart values: one has to provide `existingSecret` to create one on the fly

### ISSUE THREAD

**Issue by Morriz** [kubeapps/kubeapps#2409]
### Description:

In order to provide passwords so that those do not get re-generated every time, it is now needed to provide `postgresql .existingSecret` which, according to the docs, should point to a pre-deployed secret, when in fact it is being used to create a secret on the fly.

Sample values:

```yaml
authProxy:
  enabled: false
  external: true
postgresql:
  existingSecret: zoomazumzum
  postgresqlPassword: duzzitmadda
  replication:
    password: agennoshomo
securityContext:
  enabled: true
```

### Steps to reproduce the issue:

1. install the chart with the above values
2. observe the creation of the secret `zoomazumzum` with the intended creds
3. remove the `existingSecret: zoomazumzum` part and install the chart again
4. observe that new credentials get generated

### Describe the results you expected:

No `existingSecret` to be needed for provisioning precreated passwords.

### Additional information you deem important (e.g. issue happens only occasionally):

I addressed this downstream with bitnami but they told me to take it here. That closed issue can be found here: https://github.com/bitnami/charts/issues/5463
