### ISSUE TITLE
how can i use traefik ingress to replace nginx ingress

### ISSUE THREAD

**Issue by elysiumHL** [kubeapps/kubeapps#243]
Is that OK?
```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  namespace: kubeapps
  name: traefik-ingress
  annotations:
    kubernetes.io/ingress.class: traefik
    traefik.frontend.rule.type: PathPrefixStrip
spec:
  rules:
  - host: kubeapp.k8s
    http:
      paths:
      - path: /
        backend:
          serviceName: kubeapps-dashboard-ui
          servicePort: 8080
      - path: /api/chartsvc
        backend:
          serviceName: chartsvc
          servicePort: 8080
      - path: /api/kube
        backend:
          serviceName: kubeapps-kube-api
          servicePort: 8080
```
