### ISSUE TITLE
Upgrade TMC demo cluster with Pinniped 0.6 support

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2627]
There is an issue with authorization on our TMC demo cluster after it has auto-upgraded to Pinniped 0.6

**Comment by absoludity** [comment]
Took a look at this today and it appears that pinniped (itself, not our proxy) is unable to verify the cert of a valid https IdP, with the pinniped logs showing:

```
E0331 01:28:19.730473       1 oidc.go:224] oidc authenticator: initializing plugin: Get "https://gaz-preview.csp-vidm-prod.com/.well-known/openid-configuration": x509: certificate signed by unknown authority
```

I can verify that the tls cert is signed by digicert without any issues.

If I run the latest pinniped in a local cluster, I do not see this error. So I suspect that the TMC image may not contain the required CA certs to verify. From a brief check indeed I see that the pinniped image in my local cluster includes the certs:

```
k -n pinniped-concierge exec -ti pinniped-concierge-68d5879b54-cp2px -- ls -al /etc/ssl/certs/
total 220
drwxr-xr-x 2 root root   4096 Feb 11 13:51 .
drwxr-xr-x 3 root root   4096 Feb 11 13:51 ..
-rw-r--r-- 1 root root 213920 Feb 11 13:51 ca-certificates.crt
```

while the TMC image does not:

```
k -n vmware-system-tmc exec -ti cluster-auth-pinniped-7978779ccb-bfbsw -- ls /etc/ssl
ls: cannot access '/etc/ssl': No such file or directory
command terminated with exit code 2
```

I've asked internally to find out if this is the issue or not.

**Comment by antgamdia** [comment]
After your investigation, @absoludity, it was the CA is no longer being bundled. 
As you mentioned, in the meanwhile, the issue can be workarounded by setting `spec.tls.certificateAuthorityData`. So, as you discovered, we need to add the base64 data from the cert [DigiCert SHA2 High Assurance Server CA](https://cacerts.digicert.com/DigiCertSHA2HighAssuranceServerCA.crt.pem).

However, we were missing another thing: the `audience`. Now it is no longer `default` but the clientID used by the OIDC provider. See https://pinniped.dev/docs/howto/configure-concierge-jwt/

So the cluster is now up and running :)

Therefore, `JWTAuthenticator` for TMC will look like:
_(other environments should use: authentication.concierge.pinniped.dev)_


``` yaml
kind: JWTAuthenticator
apiVersion: authentication.concierge.pinniped.tmc.cloud.vmware.com/v1alpha1
metadata:
  name: jwt-authenticator
spec:
  issuer: https://gaz-preview.csp-vidm-prod.com
  audience: my_client_id_i_got_from_the_oidc_provider
  claims:
    groups: groups
    username: email
  tls:
    certificateAuthorityData: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVzVENDQTVtZ0F3SUJBZ0lRQk9IbnBOeGM4dk50d0N0Q3VGMFZuekFOQmdrcWhraUc5dzBCQVFzRkFEQnMKTVFzd0NRWURWUVFHRXdKVlV6RVZNQk1HQTFVRUNoTU1SR2xuYVVObGNuUWdTVzVqTVJrd0Z3WURWUVFMRXhCMwpkM2N1WkdsbmFXTmxjblF1WTI5dE1Tc3dLUVlEVlFRREV5SkVhV2RwUTJWeWRDQklhV2RvSUVGemMzVnlZVzVqClpTQkZWaUJTYjI5MElFTkJNQjRYRFRFek1UQXlNakV5TURBd01Gb1hEVEk0TVRBeU1qRXlNREF3TUZvd2NERUwKTUFrR0ExVUVCaE1DVlZNeEZUQVRCZ05WQkFvVERFUnBaMmxEWlhKMElFbHVZekVaTUJjR0ExVUVDeE1RZDNkMwpMbVJwWjJsalpYSjBMbU52YlRFdk1DMEdBMVVFQXhNbVJHbG5hVU5sY25RZ1UwaEJNaUJJYVdkb0lFRnpjM1Z5CllXNWpaU0JUWlhKMlpYSWdRMEV3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQzIKNEMvQ0pBYkliUVJmMSs4S1pBYXlmU0ltWlJhdVFrQ2J6dHlmbjNZSFBzTXdWWWNadVUrVURscVVIMVZXdE1JQwpLcS9RbU80TFFOZkUwRHR5eUJTZTc1Q3hFYW11MHNpNFF6clpDd3ZWMVpYMVFLL0lIZTFObkY5WHQ0WlFhSm4xCml0clN4d1VmcUpmSjNLU3hnb1F0eHEybG5NY1pncWFGRDE1RVdDbzNqLzAxOFFzSUp6SmE5YnVMbnFTOVVkQW4KNHQwN1FqT2pCU2pFdXlqTW1xd3JJdzE0eG52bVhuRzNTajRJKzRHM0ZoYWhuU01TVGVYWGtnaXNkYVNjdXMwWApzaDVFTldWL1V5VTUwUndLbW1NYkdaSjBhQW8zd3NKU1NNczVXcUsyNFYzQjNhQWd1Q0dpa3ladkZFb2hRY2Z0CmJadnlTQy96QS9XaWFKSlRMMTdqQWdNQkFBR2pnZ0ZKTUlJQlJUQVNCZ05WSFJNQkFmOEVDREFHQVFIL0FnRUEKTUE0R0ExVWREd0VCL3dRRUF3SUJoakFkQmdOVkhTVUVGakFVQmdnckJnRUZCUWNEQVFZSUt3WUJCUVVIQXdJdwpOQVlJS3dZQkJRVUhBUUVFS0RBbU1DUUdDQ3NHQVFVRkJ6QUJoaGhvZEhSd09pOHZiMk56Y0M1a2FXZHBZMlZ5CmRDNWpiMjB3U3dZRFZSMGZCRVF3UWpCQW9ENmdQSVk2YUhSMGNEb3ZMMk55YkRRdVpHbG5hV05sY25RdVkyOXQKTDBScFoybERaWEowU0dsbmFFRnpjM1Z5WVc1alpVVldVbTl2ZEVOQkxtTnliREE5QmdOVkhTQUVOakEwTURJRwpCRlVkSUFBd0tqQW9CZ2dyQmdFRkJRY0NBUlljYUhSMGNITTZMeTkzZDNjdVpHbG5hV05sY25RdVkyOXRMME5RClV6QWRCZ05WSFE0RUZnUVVVV2ova0s4Q0IzVTh6TmxsWkdLaUVyaFpjanN3SHdZRFZSMGpCQmd3Rm9BVXNUN0QKYVFQNHYwY0IxSmdtR2dnQzcyTmtLOE13RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJpS2xZa0Q1bTNmWFB3ZAphT3BLajRQV1VTK05hMFFXbnF4ajlkSnViSVNaaTZxQmNZUmI3VFJPc0xkNWtpbk1MWUJxOEk0ZzRYbWsvZ05ICkUrcjFoc3BaY1gzMEJKWnIwMWxZUGY3VE1TVmNHRGlFbythZmd2Mk1XNWd4VHMxNG5ocjloY3RKcXZJbmk1bHkKL0Q2cTFVRUwydFUyb2I4Y2JrZEpmMTdaU0h3RDJmMkxTYUNZSmtKQTY5YVNFYVJrQ2xkVXhQVWQxZ0plYTZ6dQp4SUNhRW5MNlZwUFgvNzh3aFFZd3Z3dC9UdjlYQlowazdZWERLL3VtZGFpc0xSYnZmWGtuc3V2Q25Rc0g2cXFGCjB3R2pJQ2hCV1VNbzBvSGpxdmJzZXp0M3RrQmlnQVZCUlFIdkZ3WSszc0F6bTJmVFlTNXloK1JwL0JJQVYwQWUKY1BVZXliUT0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
```
