### ISSUE TITLE
Test Pinniped 0.7 and managed k8s

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2662]
One of the features of the pinniped 0.7 release is that Pinniped Concierge (which we use) now support for managed K8s (EKS, AKS, GKE) using impersonation.

In addition to the normal check that 0.7 works with our current setup, we'll need to update pinniped-proxy to additionally support the impersonation method.

**Comment by antgamdia** [comment]
I can confirm that the local setup with Pinniped 0.7 in self-managed environments is working (no need to performs further changes) as usual.

However, as expected, it does not work in managed k8s envs (testing AKS atm):

![image](https://user-images.githubusercontent.com/11535726/114733672-d82b0600-9d43-11eb-875b-d3e5a4a05776.png)

Good news is that is not a 401 but an error while exchanging credentials. I'm having a look at it so that we really know which changes are required from our end to support this use case.

**Comment by absoludity** [comment]
AFAIK, concierge now has two modes. Interested to see what the difference is for us!

**Comment by antgamdia** [comment]
Some updates so far (I'll be editing this comment to ad further details)


## New features in Pinniped

There is no new authentication mechanism (afaik), the key part is still based upon a `TokenCredentialRequest`, so the whole pinniped-proxy logic is still valid.

The point here is to whom we should communicate. Whereas in a self-hosted env the cluster is somehow configured to trust the issued token by the oidc provider (via pinniped), in managed clusters pinniped cannot perform this configuration.
As a result, the API server is no longer the entity to who we have to talk.

Pinniped is automatically detecting this scenario and in v0.7 it changes its internal behavior: now it deploys a LoadBalancer service, publicly reachable aimed at replacing the usual k8s API server: it is the `ImpersonationProxy`.

The typical Pinniped use case does require having an admin account in Kubectl for configuring everything. Under the hood, it looks for a  `CredentialIssuer` to determine how to proceed. So, assuming we are in the proper kubectl context, we can run:

```
pinniped get kubeconfig   --oidc-client-id my-client-id   --oidc-scopes openid,email   --oidc-listen-port 12345 --concierge-api-group-suffix pinniped.tmc.cloud.vmware.com
```
In a managed cluster, it will detect that a LoadBalancer has been deployed:

```
 "level"=0 "msg"="discovered CredentialIssuer"  "name"="pinniped-concierge-config"
 "level"=0 "msg"="discovered Concierge operating in impersonation proxy mode"  
 "level"=0 "msg"="discovered Concierge endpoint"  "endpoint"="https://IMPERSONATION_PROXY_URL"
 "level"=0 "msg"="discovered Concierge certificate authority bundle"  "roots"=1
 "level"=0 "msg"="discovered JWTAuthenticator"  "name"="jwt-authenticator"
 "level"=0 "msg"="discovered OIDC issuer"  "issuer"="MY_ISSUER"
 "level"=0 "msg"="discovered OIDC audience"  "audience"="CLIENT_ID"
 "level"=0 "msg"="discovered OIDC CA bundle"  "roots"=2
 "level"=0 "msg"="validated connection to the cluster"  
```

And will generate a kubeconfig like: 

```yaml
...
clusters:
- cluster:
    certificate-authority-data: <redacted> # CA of the **ImpersonationProxy, not the server* 
    server: https://IMPERSONATION_PROXY_URL
  name: pinniped
...
users:
- name: pinniped
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - login
      - oidc
      - --enable-concierge
      - --concierge-api-group-suffix=pinniped.tmc.cloud.vmware.com
      - --concierge-authenticator-name=jwt-authenticator
      - --concierge-authenticator-type=jwt
      - --concierge-endpoint=https://IMPERSONATION_PROXY_URL
      - --concierge-ca-bundle-data=<redacted>
      - --issuer=MY_ISSUER
      - --client-id=CLIENT_ID
      - --scopes=openid,email
      - --listen-port=12345
      - --ca-bundle-data=<redacted>
      - --request-audience=CLIENT_ID
      command: /usr/local/bin/pinniped
      env: []
      provideClusterInfo: true
```

So, first caveat: **how can we auto-discover the impersonation proxy URL without admin permissions?**
Ideas: 
1. suggest users adding a RBAC for `CredentialIssuer:get,list` permissions. This would require us implementing the aforementioned discovery in the kubeapps side (not -only- in the pinniped proxy, afaik, since we are talking to the API directly)
2. drop the discovery part for now and simply ask the users: are you using a managed environment? If so, please add the impersonation proxy URL instead of the usual k8s API server URL.

For the sake of simplicity, let's assume the 2nd option. That is, as an admin, I know I need to provide the impersonation URL (and its CA cert) in Kubeapps instead of the usual values.

## Using the impersonation proxy in Kubeapps

I've considered two main scenarios: 

### A) Single managed cluster (eg. AKS)

Supposing we want to configure Kubeapps with OIDC in a managed cluster some steps are required; namely:
1. Install Pinniped 0.7 as usual.
2. Create a jwt authenticator, as usual.
3. Get impersonation proxy IP:  `kubectl get svc -n vmware-system-tmc pinniped-concierge-impersonation-proxy-load-balancer -o jsonpath="{.status.loadBalancer.ingress[0].ip}"`
4. Get impersonation proxy CA: `kubectl get secret pinniped-concierge-impersonation-proxy-ca-certificate -n vmware-system-tmc -o jsonpath="{.data.ca\\.crt}"`
5. Configure Kubeapps values.yaml with this cluster config:

``` yaml
clusters:
- name: aks
  apiServiceURL: https://<IP> # impersonation proxy IP
  certificateAuthorityData: <redacted> #  impersonation proxy CA
  pinnipedConfig:
    enable: true
```

Problems so far: Kubeapps core (mainly Kubeops) is not fully prepared to use different k8s auth methods rather than inCluster when being configured as a single cluster.
Even if Kubeapps seems to work, it is not really usable. For instance:
![image](https://user-images.githubusercontent.com/11535726/115043494-d9d80380-9ed4-11eb-8acf-90cca6adf597.png)


### B) Usual self-managed cluster with multicluster using an additional managed cluster (eg. AKS)

(TBD)

Having already installed Pinniped in the additional (managed) cluster, is in the usual cluster in which Kubeapps is installed where we need to add the aforementioned `clusters:` excerp.
However, it seems I'm hitting a similar error as above... still investigating what's happening.

![image](https://user-images.githubusercontent.com/11535726/115050124-b82e4a80-9edb-11eb-8615-241970b7980c.png)


### Conclusions

- The discovery of the ImpersonationProxy cannot be performed automatically without the proper permissions (get/list credential issuer, afaik). Perhaps the best approach is just asking the users for entering the proper values.
- Currently, Kubeapps does not support a single-cluster installation with OIDC with the impersonation proxy. It is due to a set of in-cluster auth assumptions. Not sure what to do here, discussion required.

- Not really important but, anyway: if using TMC in the cluster with Kubeapps installed, the Pinniped API group suffixes and namespaces should also match. That is, simply installing Pinniped with `kubectl apply -f github.com/....` won't work. You will need to change it by the proper (TMC ones) suffixes and namespaces.
