### ISSUE TITLE
Allow configuring pinniped-proxy with per-cluster namespace and suffix

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2695]
Follow-up from https://github.com/kubeapps/kubeapps/issues/2662#issuecomment-822879943

### Description:

Currently, Pinniped-Proxy is being configured globally in the values.yaml (see excerpt below). This config allows editing the API suffixes and the namespace in which Pinniped has been installed. This approach will work as long as every cluster is configured identically. 

```yaml
pinnipedProxy:
  defaultPinnipedAPISuffix: pinniped.tmc.cloud.vmware.com
  defaultPinnipedNamespace: vmware-system-tmc
  enabled: true
```

What if a cluster is using the TMC Pinniped version and we want to attach another cluster that uses de default one? Currently. it is not possible unless we make configurable this suffix and namespace per-cluster.

Edit: here, actually, we have two problems:

- [ ] Use any API suffix in Pinniped proxy. It was the main goal of my former PR https://github.com/kubeapps/kubeapps/pull/2515, but we weren't able to pass the at runtime, but at compile time. This ended up in two hardcoded API groups (the usual one and the TMC one). The crux is here: https://github.com/kubeapps/kubeapps/blob/master/cmd/pinniped-proxy/src/pinniped.rs#L47
- [ ] Make this information configurable per-cluster. This is the main problem this issue is about.
