### ISSUE TITLE
Add missing $ to use the global scope

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#2867]
### Description:

Currently, adding an `initialRepos` with `authorizationHeader` prevents the chart to be installed. It tries to retrieve `.Values.commonLabels` but, since it's under a `range` it's not in the scope.  

### Steps to reproduce the issue:

1. Install chart with a repo in `initialRepos` with `authorizationHeader`:

```yaml
apprepository:
  initialRepos:
    - authorizationHeader: Basic <redacted>
      name: myrepo
      namespace: kubeapps
      ...
```

### Describe the results you received:

```console
Error: UPGRADE FAILED: template: kubeapps/templates/apprepository/apprepositories-secret.yaml:13:18: executing "kubeapps/templates/apprepository/apprepositories-secret.yaml" at <.Values.commonLabels>: nil pointer evaluating interface {}.commonLabels
```

### Describe the results you expected:

Chart being installed

### Additional information you deem important (e.g. issue happens only occasionally):

Upstream PR already sent, waiting for Bitnami team to merge it: https://github.com/bitnami/charts/pull/6449
