### ISSUE TITLE
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)

### ISSUE THREAD

**Issue by OPSTime** [kubeapps/kubeapps#2906]
**Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)**
**kubectl -n kubeapps describe ingress kubeapps**
```
Name:             kubeapps
Namespace:        kubeapps
Address:          192.168.3.183,192.168.3.184
Default backend:  default-http-backend:80 (<error: endpoints "default-http-backend" not found>)
Rules:
  Host                         Path  Backends
  ----                         ----  --------
  kubeapps.ops.hiwhere.com.cn  
                               /   kubeapps:http (10.210.2.178:8080,10.210.3.102:8080)
Annotations:                   meta.helm.sh/release-name: kubeapps
                               meta.helm.sh/release-namespace: kubeapps
                               nginx.ingress.kubernetes.io/proxy-read-timeout: 600
Events:
  Type    Reason  Age   From                      Message
  ----    ------  ----  ----                      -------
  Normal  Sync    48m   nginx-ingress-controller  Scheduled for sync
  Normal  Sync    48m   nginx-ingress-controller  Scheduled for sync
  Normal  Sync    23m   nginx-ingress-controller  Scheduled for sync
  Normal  Sync    23m   nginx-ingress-controller  Scheduled for syn
```

**ingress-http-backend service have been added.**
**kubectl apply -f default-http-backend.service.yaml -n ingress-nginx
cat default-http-backend.service.yaml**
```
apiVersion: v1
kind: Service
metadata:
  name: default-http-backend
  namespace: ingress-nginx
spec:
  clusterIP: 10.220.160.80
  clusterIPs:
  - 10.220.160.80
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app.kubernetes.io/component: default-backend
    app.kubernetes.io/instance: ingress-nginx
    app.kubernetes.io/name: ingress-nginx
  type: ClusterIP
```

**services and endpoints of ingress-nginx:**
**kubectl -n ingress-nginx get svc,endpoints**
```
NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/default-http-backend                 ClusterIP   10.220.160.80    <none>        80/TCP    39h
service/ingress-nginx-controller-admission   ClusterIP   10.220.123.180   <none>        443/TCP   84m
service/ingress-nginx-defaultbackend         ClusterIP   10.220.37.42     <none>        80/TCP    84m

NAME                                           ENDPOINTS                               AGE
endpoints/default-http-backend                 10.210.3.218:80                         39h
endpoints/ingress-nginx-controller-admission   192.168.3.183:8443,192.168.3.184:8443   84m
endpoints/ingress-nginx-defaultbackend         10.210.3.218:8080                       84m

```

**Comment by absoludity** [comment]
Hi there @OPSTime . A backend for ingress needs to be a service or resource in the same namespace, so the error you're seeing is that you've configured the ingress in the `kubeapps` namespace (correct) to point to a service in another namespace (not correct, I don't believe). In the case of Kubeapps, you don't need to even define a new service, the ingress should point to the kubeapps frontend by default. If you look at the [chart template](https://github.com/bitnami/charts/blob/master/bitnami/kubeapps/templates/ingress.yaml#L24), it produces something like:

```
      http:
        paths:
        - backend:
            serviceName: kubeapps
            servicePort: http
          path: /
```

ie. it uses the existing Kubeapps service (of the frontend) as the backend for the ingress.

So it's not clear to me how you've got the ingress from the chart but have it pointing to something else? Let me know if that doesn't make sense.
