### ISSUE TITLE
Investigate and document Kubeapps using Azure managed AAD

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#2943]
In #2118, an issue with Azure Managed AAD's integration with oauth2-proxy was identified, with a work-around landed upstream in in oauth2-proxy.

The MS employee who landed the upstream fix didn't yet get back to document the config required to use this, so we may need to do so ourselves, as people are wanting to use this.

**Comment by antgamdia** [comment]
Status update: I've trying to use AAD in Kubeapps for writing our guides but I think I'm running into this issue 
https://github.com/oauth2-proxy/oauth2-proxy/issues/1144
I'll try to play with the oauth2proxy flags or even use the `oidc` provider instead. 

There is also a useful guide here: https://github.com/weinong/k8s-dashboard-with-aks-aad

**Comment by absoludity** [comment]
Great, thanks Antonio. Yes, we'll definitely want to be using Weinong's doc - it's specifically for using oauth2-proxy on Azure managed AAD (well, specifically for k8s dashboard, but should be the same for us).

**Comment by antgamdia** [comment]
After reading https://github.com/oauth2-proxy/oauth2-proxy/issues/1231 I just decided to drop the v1 tokens and go with the v2 ones, that are compliant with the usual `oidc` provider (no need for using the `azure` one anymore).
I'm not an azure expert at all, but I don't foresee any problems telling people in our docs they should create apps with v2 tokens.

I'm writing better docs with screenshots and so on, but, in the meanwhile, here is the minimum conf I used:

```yaml
frontend:
  proxypassAccessTokenAsBearer: true # required for azure
authProxy:
  enabled: true
  cookieSecret: redacted 
  provider: oidc 
  clientID: redacted
  clientSecret: redacted
  additionalFlags:
  - --oidc-issuer-url=https://login.microsoftonline.com/<tenant_id>/v2.0  # required for azure
  - --scope=openid 6dae42f8-4368-4678-94ff-3960e28e3630/user.read  # required for azure, exactly this string, neither '6dae42f8-4368-4678-94ff-3960e28e3630' nor 'user.read' 
```

For reasons I don't know, with v1 I was hitting the issue I mentioned yesterday, and with v2 I wasn't getting the proper token for AKS (I got a 401)... so, as I supposed it was just a problem of passing the proper scope.

However, I wasn't able to come up with `6dae42f8-4368-4678-94ff-3960e28e3630/user.read` sooner...

Here is what azure website says:
![image](https://user-images.githubusercontent.com/11535726/122095401-9f73df80-ce0d-11eb-82ca-f4fbc57bcdd8.png)

So, I tried using that instead of the `6dae42f8-4368-4678-94ff-3960e28e3630`. Next, I did try that value, but without the `/user.read`... and in a desperate attempt I just said, "ok, let's try it out all together"... and it suddenly worked :rofl:
