### ISSUE TITLE
syncer not using http proxy environment variables

### ISSUE THREAD

**Issue by r10r** [kubeapps/kubeapps#3263]
Hi there,

I tried to deploy kubeapps  today using the latest helm chart:

```
kubeapps         	kubeapps 	1       	2021-08-12 16:05:22.038411956 +0200 CEST	deployed	kubeapps-7.2.1         	2.3.3   
```

But I struggled to get the syncer working behind a http proxy. I did set the following helm chart values:

```yaml
syncImage
  initialReposProxy:
    enabled: true 
    httpProxy: "http://proxy.company.de:3128"
    httpsProxy: "http://proxy.company.de:3128"
    noProxy: ".intern.company.de,10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,127.0.0.0/8,localhost,100.64.0.0/10,.svc,.local,.example.com"
```

but the syncer jobs still fail with the following error:

```
[ruben@k8s-cluster9-controller kubeapps]$ k logs -n kubeapps pod/apprepo-kubeapps-sync-bitnami-m4vb6-phs9j
 38 time="2021-08-12T09:04:38Z" level=fatal msg="Get \"https://charts.bitnami.com/bitnami/index.yaml\": dial tcp 143.204.98.50:443: connect: connection refused"
```

## Solution

When trying to debug the issue I build and deployed a custom syncer image from https://github.com/kubeapps/kubeapps/commit/15cd52baec3f865027bc0663a4c9e81d275beb02
After that the syncer run was successful.

The syncer image in the chart version `kubeapps-7.2.1` is set to `bitnami/kubeapps-asset-syncer:2.3.3-scratch-r0`
Looking at the commit log I noticed that the http client changes that make use of the proxy environment variable (#3118) were added after v2.3.3 release.

So I think the syncer image should be updated to fix connection issues behind a http proxy.
