### ISSUE TITLE
Pass asset-syncer job image through ENV vars to work with kbld

### ISSUE THREAD

**Issue by antgamdia** [kubeapps/kubeapps#3401]
Something like:

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
spec:
  template:
    spec:
      containers:
      - args:
        - --some-img-arg=$(IMAGE_TO_USE)
        command:
        - /some-command
        image: docker.io/bitnami/kubeapps-apprepository-controller:2.0.1-scratch-r0
        name: controller
        env:
        - name: IMAGE_TO_USE
          value: "docker.io/bitnami/kubeapps-asset-syncer:2.0.1-scratch-r0"
```
