### ISSUE TITLE
[ServiceCatalog] Bindings are hardcoded to the Azure Mysql parameters and output

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#363]
I tried to create a binding for an instance of Google Cloud Pub/Sub service (instance provisioning works fine), but the binding requires some parameters that you cannot pass with Kubeapps, so the binding fails:

```
ServiceBroker returned failure; bind operation will not be retried: Status: 422; ErrorMessage: <nil>; Description: This request requires client support for asynchronous service operations.; ResponseError: <nil>
```

Also the output of the binding is hardcoded to Azure Mysql, so even if it worked, the output woudn't make sense for the pubsub case:

![screen shot 2018-06-15 at 4 54 20 pm](https://user-images.githubusercontent.com/925437/41474625-c5379ae2-70bc-11e8-82f7-92bf2cf9f823.png)

The binding create OSB definition also has an optional JSON schema. For example, in the case of the Google PubSub this is:

```
Binding Create Parameter Schema:
  $schema: http://json-schema.org/draft-04/schema#
  form:
  - roles
  - serviceAccount
  - createServiceAccount
  properties:
    createServiceAccount:
      default: false
      description: Create a new service account for MySQL binding.
      title: Create service account
      type: boolean
    roles:
      default:
      - roles/cloudsql.client
      description: The list of CloudSQL roles for this binding. Affects the level of
        access granted to the service account.
      items:
        enum:
        - roles/cloudsql.client
        type: string
      title: Roles
      type: array
      uniqueItems: true
    serviceAccount:
      description: The GCP service account to which access will be granted. For example
        <storage-service-account> or <storage-service-account>@<project-id>.iam.gserviceaccount.com
      title: Service account ID
      type: string
  required:
  - serviceAccount
  - roles
  type: object
```

We should implement the equivalent of #239 for Binding Creation as well
