### ISSUE TITLE
Kubeapps external ingress controller

### ISSUE THREAD

**Issue by edsealing** [kubeapps/kubeapps#382]
Kubernetes: v1.10
Kubeapps: v1.0.0-alpha.4

When using an ingress controller (traefik in my case), the login page will accept any string as a token and display the Kubeapps dashboard, however no functionality is available. The overall deployment yaml was created by `kubeapps up --dry-run`, then slightly modified to create a PVC for mongodb. Added an ingress (attached below).

Initial Login screen is shown:

![login_screen](https://user-images.githubusercontent.com/8030772/41973321-a055c954-79e2-11e8-8096-11b96b4ccef1.png)

When any token is provided (invalid or valid), it appears to have logged-in correctly (screenshot is with invalid token):

![invalid_token_login](https://user-images.githubusercontent.com/8030772/41973355-b988e44c-79e2-11e8-8a7c-272670612eef.png)

A javascript error is thrown when trying to access the App Repository configuration page that may help uncover the problem??:

![app_repo_error](https://user-images.githubusercontent.com/8030772/41973402-e1921ed6-79e2-11e8-844d-9e12e4bca5ae.png)

Below are the files used to configure.

[kubeapps-ingress-only.yaml](https://github.com/kubeapps/kubeapps/files/2141100/kubeapps-ingress-only.txt)

Attached are the kubeapps proxy logs showing the GET requests:

[kubeapps-proxy-logs.yaml](https://github.com/kubeapps/kubeapps/files/2141095/kubeapps-proxy-logs.txt)

[kubeapps-up.txt](https://github.com/kubeapps/kubeapps/files/2141098/kubeapps-up.txt)

**Comment by prydonius** [comment]
@edsealing the kubeapps nginx is expecting the prefixes but I think you're stripping them. From the logs, the request to the Kubernetes APIs show up as:

```
10.244.230.0 - - [27/Jun/2018:11:03:57 +0000] "GET /apis/helm.bitnami.com/v1/namespaces/default/helmreleases HTTP/1.1" 200 429 "https://apps.physical.edcop.io/apps/ns/default" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

However, when I tested with `kubeapps dashboard`, I get:

```
127.0.0.1 - - [27/Jun/2018:17:43:19 +0000] "GET /api/kube/apis/helm.bitnami.com/v1/namespaces/default/helmreleases HTTP/1.1" 200 198 "http://localhost:5000/apps/ns/default" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/67.0.3396.87 Safari/537.36"
```

Notably, the `/api/kube` prefix is still there. Can you try removing the `traefik.frontend.rule.type: PathPrefixStrip` annotation you have there and see if that fixes the issue?

**Comment by prydonius** [comment]
In fact, your Ingress should only need the one rule:

```
      - backend:
          serviceName: kubeapps
          servicePort: 8080
        path: /
```

You that will delegate the all the path matching to the kubeapps service.

**Comment by edsealing** [comment]
@prydonius Thanks for the info. Confirmed that fixed the issue. The new ingress is:

```
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "false"
    kubernetes.io/ingress.class: traefik 
  labels:
    created-by: kubeapps
    name: kubeapps
  name: kubeapps
  namespace: kubeapps
spec:
  rules:
  - host: apps.example.com
    http:
      paths:
      - backend:
          serviceName: kubeapps
          servicePort: 8080
        path: /
  tls: []
```

Works as expected. 👍
