### ISSUE TITLE
Error occred while fetching the catalog: : {"code":5,"message":"Not Found"}.

### ISSUE THREAD

**Issue by doddatpivotal** [kubeapps/kubeapps#4038]
### Description:

I've deployed the kubeapps helm chart v7.4.0 using authProxy for OIDC and PinnipedProxy.  OIDC issuer is dex deployed on the cluster.  I have been able to access kubeapps and perform OIDC login.  Using a user who has no permissions on the cluster, I get expected Kubeapps messaging saying that I don't have permissions.  When I log out and log in with a user who does have permissions, I pass through the previous stage, but then get this error message...

An error occurred while fetching the catalog: {"code":5,"message":"Not Found"}. 

### Additional information you deem important (e.g. issue happens only occasionally):

Here is my chart values file...
```
useHelm3: true
allowNamespaceDiscovery: true
ingress:
  enabled: true
  certManager: true
  hostname: kubeapps.riverrun.tkg-azure-e2-lab.winterfell.life
  tls: true
  annotations:
    ingress.kubernetes.io/force-ssl-redirect: "true"
    ingress.kubernetes.io/proxy-body-size: "0"
    kubernetes.io/ingress.class: "contour"
    cert-manager.io/cluster-issuer: "letsencrypt-contour-cluster-issuer"
    kubernetes.io/tls-acme: "true"
# Auth Proxy for OIDC support
# ref: https://github.com/kubeapps/kubeapps/blob/master/docs/user/using-an-OIDC-provider.md
authProxy:
  enabled: true
  provider: oidc
  cookieSecret: REDACTED
  clientID: kubeapps
  clientSecret: REDACTED
  additionalFlags:
    - --oidc-issuer-url=https://REDACTED
# Pinniped Support
# https://liveandletlearn.net/post/kubeapps-on-tanzu-kubernetes-grid-13-part-2/
pinnipedProxy:
  enabled: true
  defaultAuthenticatorName: kubeapps-jwt-authenticator
  image:
    repository: bitnami/kubeapps-pinniped-proxy
clusters:
  - name: default
    pinnipedConfig:
      enable: true
apprepository:
  initialRepos:
    - name: vac-repo
      url: https://charts.app-catalog.vmware.com/demo
```

### Version of Helm, Kubeapps and Kubernetes:

- Output of `helm version`:

```
version.BuildInfo{Version:"v3.5.4", GitCommit:"1b5edb69df3d3a08df77c9902dc17af864ff05d1", GitTreeState:"clean", GoVersion:"go1.15.11"}
```

- Output of `helm list -n <kubeapps-namespace> <kubeapps-release-name>`:

```
$ helm list -n kubeapps
NAME            NAMESPACE       REVISION        UPDATED                                 STATUS          CHART           APP VERSION
kubeapps        kubeapps        1               2022-01-06 10:15:54.066851 -0500 EST    deployed        kubeapps-7.4.0  2.4.0      ```

- Output of `kubectl version`:

```
 $ kubectl version
Client Version: version.Info{Major:"1", Minor:"20+", GitVersion:"v1.20.4-dirty", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"dirty", BuildDate:"2021-03-15T10:03:32Z", GoVersion:"go1.16.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.3+vmware.1", GitCommit:"1e08ca8eda6b74527882c9baee8e05620d24c96a", GitTreeState:"clean", BuildDate:"2021-11-01T20:40:20Z", GoVersion:"go1.16.9", Compiler:"gc", Platform:"linux/amd64"}```
