### ISSUE TITLE
Token validation doesn't work in development

### ISSUE THREAD

**Issue by shinystaratnight** [kubeapps/kubeapps#4161]
I have deployed the kubeapps in the Kubenetes cluster on localhost following [Get Started with Kubeapps](https://github.com/kubeapps/kubeapps/blob/main/docs/user/getting-started.md).
It works at http://127.0.0.1:8080/.

And I followed the [Kubeapps Dashboard Developer Guide](https://github.com/kubeapps/kubeapps/blob/main/docs/developer/dashboard.md).
I tried both ways with & without telepresence.

I can confirm that the proxying is working well. 
What I am stuck in is that I can't login using the token in development. In the inspector window, I could find out that the called api endpoints are different in development.
For your references, let me attach the pictures of inspector window.

This is what I can see in the deployed kubeapps. (when working)
![image](https://user-images.githubusercontent.com/56991237/150956112-f6e5c204-3a90-4a03-aaea-c10e3a988fd8.png)

This is what I can see in development. (when not working)
![image](https://user-images.githubusercontent.com/56991237/150956408-93f83983-8dda-4a89-8f49-4b33b80e0c68.png)

Can anyone of you kindly help me out?

**Comment by antgamdia** [comment]
Hi @shinystaratnight 

thanks for your interest in running Kubeapps in development (happy to discuss what are you trying to develop in the [slack channel](https://kubernetes.slack.com/messages/kubeapps) and help you if you need something).
We are currently revisiting our docs and, perhaps, some steps are not as up to date as we might want to be. 

Which component are you trying to develop? The `dashboard` ?
If so, what I do is:

1. I have a k8s cluster (v1.21) with Kind
2. I've installed Kubeapps normally with `helm upgrade --install kubeapps ./chart/kubeapps -n kubeapps --create-namespace  --values values.yaml` (values below)
3. I add a `proxy` in the `dashboard/package.json` pointing to the URL where the actual dashboard is running (in your case it seems to be  `http://127.0.0.1:8080`)
4. I run `yarn start`
5.  I get the token with `kubectl get secret $(kubectl get serviceaccount kubeapps-operator -o jsonpath='{range .secrets[*]}{.name}{"\n"}{end}' | grep kubeapps-operator-token) -o jsonpath='{.data.token}' -o go-template='{{.data.token | base64decode}}' && echo`
    1. Assuming you already have a privileged `kubeapps-operator` SA, if not:
        1. `kubectl create serviceaccount kubeapps-operator -n default`
        2. `kubectl create clusterrolebinding kubeapps-operator -n default --clusterrole=cluster-admin --serviceaccount=default:kubeapps-operator`


We also have some makefile files that might be useful: https://github.com/kubeapps/kubeapps/blob/main/docs/developer/using-makefiles.md

Let us know if you still have some issues!

_dashboard/package.yaml_
```json
{
  "name": "dashboard",
  "version": "0.1.0",
  "private": true,
  "homepage": "./",
  "proxy": "https://localhost", // <--- this is the new line
....
```


_values.yaml_
```yaml

clusters:
  - name: default
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/proxy-read-timeout: "600"
  enabled: true
  hostname: localhost
  tls: true
  selfSigned: true
frontend:
  replicaCount: 1
dashboard:
  replicaCount: 1
kubeops:
  replicaCount: 1
kubeappsapis:
  replicaCount: 1
  enabledPlugins:
    - helm
    - kapp-controller
    - resources
postgresql:
  replication:
    enabled: false
  postgresqlPassword: xtbvQ5NSXz

```
