### ISSUE TITLE
Not able to to deploy an application

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#4323]
### Discussed in https://github.com/kubeapps/kubeapps/discussions/4320

<div type='discussions-op-text'>

<sup>Originally posted by **junoriosity** February 21, 2022</sup>
As mentioned earlier (https://github.com/kubeapps/kubeapps/discussions/4219) I deployed kubeapps with 

```
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-crds.yaml
kubectl apply -f https://get.pinniped.dev/v0.13.0/install-pinniped-concierge-resources.yaml

cat <<EOF | kubectl apply -f -
kind: JWTAuthenticator
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
metadata:
  name: jwt-authenticator
spec:
  issuer: https://my-auth.eu.auth0.com/
  audience: my-client-id
  claims:
    groups: groups
    username: email
EOF

cat <<EOF | kubectl apply -f -
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: kubeapps-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - apiGroup: rbac.authorization.k8s.io
    kind: User
    name: test@test.com
  - apiGroup: rbac.authorization.k8s.io
    kind: Group
    name: kubeapps-operators
EOF

kubectl create ns kubeapps
helm install kubeapps bitnami/kubeapps --namespace kubeapps -f myvals.yaml 
```

where `myvals.yaml` is

```
useHelm3: true
authProxy:
  additionalFlags:
    - --oidc-issuer-url=https://my-auth.eu.auth0.com/ # Example: https://antoniogamez.eu.auth0.com/  # mind the last "/" character
  # If you are using a different ingress config, you might need to tweak these flags. More info in the "oauth2-proxy" official docs
    - --redirect-url=http://127.0.0.1:3000/oauth2/callback
    # - --cookie-domain=localhost
    # - --whitelist-domain=localhost
    # - --cookie-secure=false
  clientID: my-client-id
  clientSecret: my-client-secret
  cookieSecret: bm90LWdvb2Qtc2VjcmV0Cg==
  enabled: true
  provider: oidc

pinnipedProxy:
  enabled: true # if using Pinniped, you'll need to enable this option here
#  defaultAuthenticatorType: jwt
#  defaultAuthenticatorName: jwt-authenticator

clusters:
  - name: default
    apiServiceURL: https://... # impersonation proxy URL
    certificateAuthorityData: ... #  impersonation proxy CA
    pinnipedConfig:
      enabled: true
```

With this I can reach the catalog panel

<img width="1649" alt="kubeapps_catlog" src="https://user-images.githubusercontent.com/5286536/154947901-e65eff59-757c-466b-a921-59326eb762ce.png">

But when I click on one (like airflow), I receive

<img width="1652" alt="kubeapps_airflow" src="https://user-images.githubusercontent.com/5286536/154948030-b92e8ff2-d776-484c-b08f-c2744f19ceba.png">

Do you know how to fix that?</div>
