### ISSUE TITLE
asset-syncer sends empty `Authorization` header for public repos

### ISSUE THREAD

**Issue by absoludity** [kubeapps/kubeapps#4345]
### Description:

Originally [reported by Chris on slack](https://kubernetes.slack.com/archives/C9D3TSUG4/p1645724386707139).

Currenly, when pulling the index of a *public* helm repository, the asset-syncer sends an empty `Authorization` header:

https://github.com/kubeapps/kubeapps/blob/v2.4.3/cmd/asset-syncer/server/utils.go#L729

Chris is seeing a 403 returned with a public repo on GCP, though I've not been able to reproduce that with curl, only getting a 401 if I send an actual auth value:

```
curl -sI https://appvia-community.storage.googleapis.com/index.yaml | head -n1
HTTP/2 200 

curl -sI https://appvia-community.storage.googleapis.com/index.yaml -H "Authorization: " | head -n1
HTTP/2 200 

curl -sI https://appvia-community.storage.googleapis.com/index.yaml -H "Authorization: anything" | head -n1
HTTP/2 401 

curl -sI https://appvia-community.storage.googleapis.com/index.yaml -H "Authorization:" | head -n1 
HTTP/2 200 

```

I'll ask for more info.

**Comment by absoludity** [comment]
According to the http spec, an Authorization header should never be empty, so we should fix that either way, but just want to verify that we'll be fixing the original issue as well (or if not, how we can).

**Comment by chrisns** [comment]
sorry! sent message and then left the office 🤣 thanks for doing the leg work and validating i’m not mad and raising the issue.

If you do curl -v https://appvia-community.storage.googleapis.com/index.yaml -H "Authorization: " you’ll see in the request payload that curl is apparently not sending the authorization header without a value set

**Comment by chrisns** [comment]
My workaround for now with a reverse proxy that removes the header and adding the helm repo with a url of `http://proxy.kubeapps.svc.cluster.local`

```yaml
kind: Deployment
apiVersion: apps/v1
metadata:
  name: proxy
  namespace: kubeapps
  labels:
    name: proxy
spec:
  replicas: 3
  selector:
    matchLabels:
      name: proxy
  template:
    metadata:
      labels:
        name: proxy
    spec:
      containers:
        - name: proxy
          image: "nginx"
          ports:
            - containerPort: 8080
              name: http
          volumeMounts:
            - mountPath: /etc/nginx
              name: nginx-config
      volumes:
        - name: nginx-config
          configMap:
            name: proxy
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
  namespace: kubeapps
data:
  nginx.conf: |-
    events {}
    http {
      server {
        listen 8080 default_server;
        listen [::]:8080 default_server;
        proxy_set_header Authorization "";

        location / {
            proxy_pass https://appvia-community.storage.googleapis.com/;
        }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  namespace: kubeapps
  name: proxy
spec:
  ports:
    - name: http
      port: 80
      targetPort: http
  selector:
    name: proxy
```
