### ISSUE TITLE
[fluxv2] non-FQDN chart url fails on chart view

### ISSUE THREAD

**Issue by hongkunyoo** [kubeapps/kubeapps#4381]
### Background

I am using fluxv2 plugin. I have a repository launched by chartmuseum with following `index.yaml`:

```yaml
apiVersion: v1
entries:
  airflow:
  - apiVersion: v2
    appVersion: 2.1.4
    created: "2022-02-18T11:33:37.336580189Z"
    dependencies:
    - condition: postgresql.enabled
      name: postgresql
      repository: https://charts.bitnami.com/bitnami
      version: 10.9.4
    description: Helm chart to deploy Apache Airflow, a platform to programmatically
      author, schedule, and monitor workflows
    digest: 0bebbb733539200082bc73baaaf44287c90874ff1ce57ef306baa13b59082cf5
    home: https://airflow.apache.org/
    icon: https://airflow.apache.org/docs/apache-airflow/stable/_images/pin_large.png
    keywords:
    - apache
    - airflow
    - workflow
    - scheduler
    maintainers:
    - email: dev@airflow.apache.org
      name: Apache Airflow PMC
    name: airflow
    sources:
    - https://github.com/apache/airflow
    urls:
    - charts/airflow-1.0.0.tgz    # <--- LOOK HERE
    version: 1.0.0
generated: "2022-02-18T11:33:37Z"
serverInfo: {}
```

The URL of the chart only has the path, not the full URL: 

```yaml
urls:
- charts/airflow-1.0.0.tgz
```

This works well with `helm` and `HelmRepository`.

Ref: https://github.com/helm/helm/pull/3065

### Problem

However when I clicked `airflow` chart in Catalog on dashboard, following error occurs.

- Frontend dashboard:

```
Unable to fetch package: Unable to get the available package detail for the package "$REPO_NAME%2Fairflow" using the plugin "fluxv2.packages": rpc error: code = Internal desc = failed to load details for chart [$REPO_NAME/airflow]
```

- kubeappsapi backend:

```
E0303 11:55:06.678894       1 chart_cache.go:222] Error processing helmcharts:$NAMESPACE:$REPO_NAME/airflow-1.0.0 (giving up): Get "charts/airflow-1.0.0.tgz": unsupported protocol scheme ""
```

It seems that `ChartCache` does not handle non-FQDN URLs (https://github.com/kubeapps/kubeapps/blob/main/cmd/kubeapps-apis/plugins/fluxv2/packages/v1alpha1/cache/chart_cache.go#L578)

I have solved it by changing to FQDN URL in `index.yaml`, however It might be great if `kubeappsapis` can also handle non-FQDN URL.

By the way, I have deployed `v2.4.3` kubeapps and find out the features that I asked has been applied. Thank you!
