### ISSUE TITLE
Display status message for Service Bindings

### ISSUE THREAD

**Issue by migmartri** [kubeapps/kubeapps#455]
it seems that the binding went through two transitions

```
status:
  asyncOpInProgress: false
  conditions:
  - lastTransitionTime: 2018-08-09T03:32:33Z
    message: Orphan mitigation was completed successfully
    reason: OrphanMitigationSuccessful
    status: "False"
    type: Ready
  - lastTransitionTime: 2018-08-09T03:32:46Z
    message: 'ServiceBroker returned failure; bind operation will not be retried:
      Status: 500; ErrorMessage: <nil>; Description: <nil>; ResponseError: <nil>'
    reason: ServiceBindingReturnedFailure
    status: "True"
    type: Failed
  orphanMitigationInProgress: false
  reconciledGeneration: 1
  unbindStatus: Succeeded
```

Being the last one apparently a failed state (type: Failed,  unbindStatus: Succeeded), the error message is quite useless though. 

In any case, the UI seems to show only the first transition.

![selection_633](https://user-images.githubusercontent.com/24523/43876628-d48f0f80-9b4a-11e8-8c50-2005fd2d7ff4.png)

Should it show the latest one? Did the binding actually succeed? Failed?
