### ISSUE TITLE
update repository list

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#628]
step 1 deploy with helm kubeapps with a list of repo
step 2 update with helm kubeapps with same list of repo + one new

When upgrade the list of repository in chart deployment kubeapps, the list in ui is not updated.

**Comment by andresmgot** [comment]
It seems that the `app repository-jobs-bootstrap` is not being re-run when upgrading the application. Since helm already released 2.10, maybe this issue can be fixed if we use the hook `crd-install` for that. WDYT @prydonius ?

**Comment by prydonius** [comment]
We don't want to use the `crd-install` hook since that means the chart won't work for older versions of Helm. We could update the bootstrap job to run on post-upgrade as well as post-install, although this will force re-syncing every repository when upgrading.

@obeyler maybe instead you could add new repos using the AppRepository kind using Kubernetes manifests, e.g.:

```
apiVersion: v1
items:
apiVersion: kubeapps.com/v1alpha1
kind: AppRepository
metadata:
  name: myrepo
spec:
  url: https://charts.myrepo.com/
  type: helm
```

Is there any reason you'd prefer to do this using the chart values?
