### ISSUE TITLE
Feature request: lock repository list

### ISSUE THREAD

**Issue by obeyler** [kubeapps/kubeapps#629]
Add an option in chart value to disable opportuity to change the list of repo in ui : no delete/no add repo just refresh button

**Comment by andresmgot** [comment]
That is something that should be doable with RBAC roles. @obeyler if you want to prevent users from deleting `apprepositories` you should remove that capability for any role or clusterrole associated to the `token` you are using for logging in the app. 

Having said that we could also hide the `Delete` and `Update` buttons if the user doesn't have rights to modify them but that is just something nice to have.

**Comment by prydonius** [comment]
> That is something that should be doable with RBAC roles. @obeyler if you want to prevent users from deleting apprepositories you should remove that capability for any role or clusterrole associated to the token you are using for logging in the app.

Indeed, RBAC is the way to control this currently. Take a look at this [document](https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md) for more configuring permissions in a more fine-grained way. In particular, you can disable the ability to delete/add repos by only giving accounts Read access to App Repositories: https://github.com/kubeapps/kubeapps/blob/master/docs/user/access-control.md#app-repositories.

Note, the read role won't allow users to update repos by default, you'll need to edit the role and add `update` as well as `list` and `get`:

```
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: kubeapps-repositories-read
rules:
- apiGroups: 
  - kubeapps.com
  resources: 
  - apprepositories
  verbs: 
  - list
  - get
  - update
```

> Having said that we could also hide the Delete and Update buttons if the user doesn't have rights to modify them but that is just something nice to have.

It might be confusing, from a UX perspective, to hide the buttons. What if the user just have incorrect permissions and was expecting to be able to delete them?
