### ISSUE TITLE
need instruction to deploy kubeapps on openshift

### ISSUE THREAD

**Issue by thatsk** [kubeapps/kubeapps#670]
```
helm repo add bitnami https://charts.bitnami.com/bitnami
helm install --name kubeapps --namespace kubeapps bitnami/kubeapps
oc get pods
NAME                                                          READY     STATUS    RESTARTS   AGE
kubeapps-84bf67c978-f9gbb                                     1/1       Running   0          2d
kubeapps-internal-apprepository-controller-7bc57bf789-97b94   1/1       Running   0          2d
kubeapps-internal-chartsvc-6df4cd6477-5vs9w                   0/1       Running   849        2d
kubeapps-internal-dashboard-5cdc786d85-7vwmz                  1/1       Running   0          2d
kubeapps-internal-tiller-proxy-55d9558c78-k8fg8               1/1       Running   0          2d
```
I get all is good but when i try to access ui.
it chartsvc pod going crashloopbackoff 
```YAML
NAME                                                          READY     STATUS             RESTARTS   AGE
kubeapps-84bf67c978-f9gbb                                     1/1       Running            0          2d
kubeapps-internal-apprepository-controller-7bc57bf789-97b94   1/1       Running            0          2d
kubeapps-internal-chartsvc-6df4cd6477-5vs9w                   0/1       CrashLoopBackOff   849        2d
kubeapps-internal-dashboard-5cdc786d85-7vwmz                  1/1       Running            0          2d
kubeapps-internal-tiller-proxy-55d9558c78-k8fg8               1/1       Running            0          2d

Name:           kubeapps-internal-chartsvc-6df4cd6477-5vs9w
Namespace:      kubeapps
Node:          master/10.174.180.27
Start Time:     Thu, 20 Sep 2018 03:27:04 +0000
Labels:         app=kubeapps-internal-chartsvc
                pod-template-hash=2890782033
                release=kubeapps
Annotations:    openshift.io/scc=restricted
Status:         Running
IP:             10.130.0.25
Controlled By:  ReplicaSet/kubeapps-internal-chartsvc-6df4cd6477
Containers:
  chartsvc:
    Container ID:  docker://7599df35008a0c060b26294e08854421a33f8b7e48d71760c90ce3a803d9757d
    Image:         docker.io/kubeapps/chartsvc:v1.0.0-beta.0
    Image ID:      docker-pullable://docker.io/kubeapps/chartsvc@sha256:b18e87bd9d7a7dd75521b7ce154b60db839a5b32388ad3c09e11dd348d107227
    Port:          8080/TCP
    Command:
      /chartsvc
    Args:
      --mongo-user=root
      --mongo-url=kubeapps-mongodb
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Sat, 22 Sep 2018 08:23:58 +0000
      Finished:     Sat, 22 Sep 2018 08:25:08 +0000
    Ready:          False
    Restart Count:  849
    Liveness:       http-get http://:8080/live delay=60s timeout=5s period=10s #success=1 #failure=3
    Readiness:      http-get http://:8080/ready delay=0s timeout=5s period=10s #success=1 #failure=3
    Environment:
      MONGO_PASSWORD:  <set to the key 'mongodb-root-password' in secret 'kubeapps-mongodb'>  Optional: false
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-r7mln (ro)
Conditions:
  Type           Status
  Initialized    True
  Ready          False
  PodScheduled   True
Volumes:
  default-token-r7mln:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-r7mln
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  node-role.kubernetes.io/compute=true
Tolerations:     <none>
Events:
  Type     Reason     Age                  From                                      Message
  ----     ------     ----                 ----                                      -------
  Normal   Pulled     1h (x832 over 2d)    kubelet, master  Container image "docker.io/kubeapps/chartsvc:v1.0.0-beta.0" already present on machine
  Warning  Unhealthy  57m (x1672 over 2d)  kubelet, master  Liveness probe failed: Get http://10.130.0.25:8080/live: dial tcp 10.130.0.25:8080: getsockopt: connection refused
  Warning  Unhealthy  12m (x6143 over 2d)  kubelet, master  Readiness probe failed: Get http://10.130.0.25:8080/ready: dial tcp 10.130.0.25:8080: getsockopt: connection refused
  Warning  BackOff    2m (x10116 over 2d)  kubelet, master  Back-off restarting failed container

```
