### ISSUE TITLE
Unable to login in Kubeapps deployed on Openshift (minishift)

### ISSUE THREAD

**Issue by sl33kr** [kubeapps/kubeapps#698]
I am attempting to spin up Kubeapps inside Openshift (using minishift). Kubeapps starts as expected however when attempting to login for the first time using a user token the below error is returned from 
`http://kubeapps-myproject.10.0.75.240.nip.io/api/tiller-deploy/v1/namespaces/default/releases`

```
an error on the server ("This request caused apiserver to panic. Look in the logs for details.") has prevented the request from succeeding (post selfsubjectrulesreviews.authorization.k8s.io)
```

Is there a way to work around this or is it a minishift/openshift issue?

**Comment by prydonius** [comment]
Thanks for filing the issue @sl33kr. Could you let us know what version fo OpenShift you're using? A quick look at the docs suggest that the issue might be that the SelfSubjectRulesReviews API is under the `authorization.openshift.io` api group instead of `authorization.k8s.io` in vanilla Kubernetes.

We will need to look into how to use this API across both vanilla Kubernetes and OpenShift.

cc @andresmgot

**Comment by sl33kr** [comment]
Hi sorry for some reason I thought I had included that.

I'm running in minishift 1.24.0 using Openshift v3.10.0.

**Comment by migmartri** [comment]
I could confirm the issue. 

```
{
  "code": 401,
  "message": "an error on the server (\"This request caused apiserver to panic. Look in the logs for details.\") has prevented the request from succeeding (post selfsubjectrulesreviews.authorization.k8s.io)"
}
```

this was the entry in the log

```
W1022 14:23:42.775043       1 reflector.go:341] github.com/openshift/origin/vendor/k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:86: watch of *rbac.ClusterRole ended with: The resourceVersion for the provided watch is too old.
E1022 14:23:44.798046       1 watcher.go:208] watch chan error: etcdserver: mvcc: required revision has been compacted
```

**Comment by aland-zhang** [comment]
Hello everyone, login with token http://kubeapps-kubeapps.10.10.5.180.nip.io/login ,show error "There was an error connecting to the Kubernetes API. Please check that your token is valid". 
But my token is correct，What is the problem？
Executed inside the container kubeapps-internal-tiller-proxy
```
curl -k https://kubernetes.default
{
  "paths": [
    "/api",
    "/api/v1",
    "/apis",
    "/apis/",
    "/apis/admissionregistration.k8s.io",
    "/apis/admissionregistration.k8s.io/v1beta1",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/apis/apiregistration.k8s.io",
    "/apis/apiregistration.k8s.io/v1",
    "/apis/apiregistration.k8s.io/v1beta1",
    "/apis/apps",
    "/apis/apps.openshift.io",
    "/apis/apps.openshift.io/v1",
    "/apis/apps/v1",
    "/apis/apps/v1beta1",
    "/apis/apps/v1beta2",
    "/apis/policy",
    "/apis/policy/v1beta1",
    "/apis/project.openshift.io",
    "/apis/project.openshift.io/v1",
    "/apis/quota.openshift.io",
    "/apis/quota.openshift.io/v1",
    "/apis/rbac.authorization.k8s.io",
    "/apis/rbac.authorization.k8s.io/v1",
    "/apis/rbac.authorization.k8s.io/v1beta1",
    "/apis/rbac.istio.io",
    "/apis/rbac.istio.io/v1alpha1",
    "/apis/rook.io",
    "/apis/rook.io/v1alpha2",
    "/apis/route.openshift.io",
    "/apis/route.openshift.io/v1",
    "/apis/scheduling.k8s.io",
    "/apis/scheduling.k8s.io/v1beta1",
    "/apis/security.openshift.io",
    "/apis/security.openshift.io/v1",
    "/apis/serving.knative.dev",
    "/apis/serving.knative.dev/v1alpha1",
    "/apis/sources.eventing.knative.dev",
    "/apis/sources.eventing.knative.dev/v1alpha1",
    "/apis/storage.k8s.io",
    "/apis/storage.k8s.io/v1",
    "/apis/storage.k8s.io/v1beta1",
    "/apis/template.openshift.io",
    "/apis/template.openshift.io/v1",
    "/apis/user.openshift.io",
    "/apis/user.openshift.io/v1",
    "/healthz",
    "/healthz/autoregister-completion",
    "/healthz/etcd",
    "/healthz/log",
    "/healthz/ping",
    "/healthz/poststarthook/apiservice-openapi-controller",
    "/healthz/poststarthook/apiservice-registration-controller",
    "/healthz/poststarthook/apiservice-status-available-controller",
    "/healthz/poststarthook/authorization.openshift.io-bootstrapclusterroles",
    "/healthz/poststarthook/authorization.openshift.io-ensureopenshift-infra",
    "/healthz/poststarthook/bootstrap-controller",
    "/healthz/poststarthook/ca-registration",
    "/healthz/poststarthook/generic-apiserver-start-informers",
    "/healthz/poststarthook/image.openshift.io-apiserver-caches",
    "/healthz/poststarthook/kube-apiserver-autoregistration",
    "/healthz/poststarthook/oauth.openshift.io-startoauthclientsbootstrapping",
    "/healthz/poststarthook/openshift.io-restmapperupdater",
    "/healthz/poststarthook/openshift.io-startinformers",
    "/healthz/poststarthook/openshift.io-webconsolepublicurl",
    "/healthz/poststarthook/project.openshift.io-projectauthorizationcache",
    "/healthz/poststarthook/project.openshift.io-projectcache",
    "/healthz/poststarthook/quota.openshift.io-clusterquotamapping",
    "/healthz/poststarthook/rbac/bootstrap-roles",
    "/healthz/poststarthook/scheduling/bootstrap-system-priority-classes",
    "/healthz/poststarthook/security.openshift.io-bootstrapscc",
    "/healthz/poststarthook/start-apiextensions-controllers",
    "/healthz/poststarthook/start-apiextensions-informers",
    "/healthz/poststarthook/start-kube-aggregator-informers",
    "/healthz/ready",
    "/metrics",
    "/oapi",
    "/oapi/v1",
    "/openapi/v2",
    "/swagger-2.0.0.json",
    "/swagger-2.0.0.pb-v1",
    "/swagger-2.0.0.pb-v1.gz",
    "/swagger.json",
    "/swaggerapi",
    "/version",
    "/version/openshift"
  ]
}
Execute with the same token，can return correct data

kubectl get pods --token=IabiX75opbh9fxJrQN-bov67eCeO9OLawgl4LgiHblY                                             
NAME                                                         READY     STATUS    RESTARTS   AGE
kubeapps-77bbf8957f-swnwq                                    1/1       Running   0          46m
kubeapps-internal-apprepository-controller-6d647cffd-4d5cx   1/1       Running   0          33m
kubeapps-internal-chartsvc-79b55db4b-hvk42                   1/1       Running   0          47m
kubeapps-internal-dashboard-54d45495cc-sw5kf                 1/1       Running   0          14m
kubeapps-internal-tiller-proxy-7f67dc4986-rklhp              1/1       Running   0          33m
kubeapps-mongodb-5458b5c6f8-sqbx5                            1/1       Running   0          3d

curl --header "Authorization: Bearer $TOKEN" -k https://kubernetes.default/v1/namespaces/default/releases
{
  "paths": [
    "/apis",
    "/apis/",
    "/apis/apiextensions.k8s.io",
    "/apis/apiextensions.k8s.io/v1beta1",
    "/metrics",
    "/version"
  ]
}
```

**Comment by prydonius** [comment]
Hey @aland-zhang, unfortunately OpenShift isn't supported yet by Kubeapps, see https://github.com/kubeapps/kubeapps/issues/676#issuecomment-436015118 for more information about the present issues.

Do you have the logs from your API server? There might be a similar issue as above, where the API server crashes when connecting from Kubeapps.

**Comment by absoludity** [comment]
This is reproducible with OpenShift 3.10 directly with kubectl:
```
kubectl create -f - -o yaml << EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectRulesReview
spec:
  namespace: default 
EOF            
Error from server (InternalError): error when creating "STDIN": an error on the server ("This request caused apiserver to panic. Look in the logs for details.") has prevented the request from succeeding (post selfsubjectrulesreviews.authorization.k8s.io)

**Comment by absoludity** [comment]
This is reproducible with OpenShift 3.10 via kubectl:

```
kubectl create -f - -o yaml << EOF
apiVersion: authorization.k8s.io/v1
kind: SelfSubjectRulesReview
spec:
  namespace: default 
EOF
Error from server (InternalError): error when creating "STDIN": an error on the server ("This request caused apiserver to panic. Look in the logs for details.") has prevented the request from succeeding (post selfsubjectrulesreviews.authorization.k8s.io)
```

As @prydonius guessed, using the openshift specific api group works fine in 3.10:

```
kubectl create -f - -o yaml << EOF                                                                                                                                                   
apiVersion: authorization.openshift.io/v1                                                                                                                                                                                         
kind: SelfSubjectRulesReview                                                                                                                                                                                                      
spec:                                                                                                                                                                                                                            
  namespace: default                                                                                                                                                                                                              
EOF
                                                                                
apiVersion: authorization.openshift.io/v1                                      
kind: SelfSubjectRulesReview           
spec:                                                                                                                 
  scopes: null                               
status:                                
  rules:                                                                                                                                                                                                                          
  - apiGroups:                                                                                                                                                                              
    - ""                                                                                                                                                                                    
...
```

On a 3.11 Openshift cluster, both api groups work:
```
$ oc version
oc v3.11.0+0cbc58b                   
kubernetes v1.11.0+d4cacc0          
features: Basic-Auth GSSAPI Kerberos SPNEGO
                                 
Server https://192.168.42.36:8443 
kubernetes v1.11.0+d4cacc0       

$ kubectl create -f - -o yaml << EOF > rulesreview-k8s.yaml
apiVersion: authorization.k8s.io/v1                                                     
kind: SelfSubjectRulesReview             
spec:                                      
  namespace: default                
EOF                              
                                 

$ kubectl create -f - -o yaml << EOF > rulesreview-openshift.yaml
apiVersion: authorization.openshift.io/v1               
kind: SelfSubjectRulesReview     
spec:
  namespace: default
EOF

```

The output is not identical (openshift appears to group the output differently).

Anyway, for Kubeapps to therefore support Openshift pre 3.11, we'd need to either stop using this apigroup, or provide an `--authorization-api-group` arg which defaults to `authorization.k8s.io` but can be set as required for openshift.
