### ISSUE TITLE
Authorization issues

### ISSUE THREAD

**Issue by jaypvee** [kubeapps/kubeapps#731]
Hi im new to using k8s and have recently used kubeapps on a minikube cluster. I have however switched to using a cluster from canonical (Juju charms), so far it is the default cluster nothing has been adjusted. When i run the helm install command i get the following error: 
![image](https://user-images.githubusercontent.com/43379160/46952037-fab40980-d089-11e8-8cee-ecd68b679949.png)
I know it has to do with authorization but i do not know how to fix this issue.

**Comment by andresmgot** [comment]
Hi @jaypvee, your issue seems to be related with the fact that Tiller (helm server side) doesn't have permissions enough to create the resources required by Kubeapps. Check this thread for a possible solution: https://github.com/kubeapps/kubeapps/issues/667#issuecomment-423663944 

@migmartri what do you think about creating a FAQ for issues like this?

**Comment by jaypvee** [comment]
So I've followed the advice of that issue thread and created the sa and roles but i still get the same issue. 
![image](https://user-images.githubusercontent.com/43379160/47006691-ccd8ce80-d136-11e8-9cb5-ba5df02bb76c.png)

**Comment by andresmgot** [comment]
It seems that you cluster doesn't have the clusterrole `cluster-admin` (that is normally present in every kubernetes cluster). You can manually create it executing:

```
kubectl create -f - -o yaml  << EOF
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-admin
rules:
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - '*'
- nonResourceURLs:
  - '*'
  verbs:
  - '*'
EOF
```
