### ISSUE TITLE
Chartmuseum can not be added to app repositories

### ISSUE THREAD

**Issue by chenlein** [kubeapps/kubeapps#903]
When I deployed a chartmuseum service, I tried to deploy kubeapps chart using by helm, and I provide the override.yml to override default repositories. After I log in to the kubeapps UI, I can see some applications instance that has been deployed by helm at the Applications navigate. However, the catalog is empty. I tried to add `http://servieName.namespaceName:8080` to repositories, no response occurred. I don't know what happend.

override.yml:
```yaml
ingress:
  enabled: true
  hosts:
    - name: kubeapps.kube.sz
      path: /
apprepository:
  initialRepos:
    - name: museum
      url: http://chartmuseum.kube.sz/
```
``` shell
[root@master-0 charts]# helm install kubeapps-1.1.0.tgz -f override.yml --name kubeapps --namespace ns-support
[root@master-0 charts]# kubectl create serviceaccount kubeapps-operator -n ns-support
[root@master-0 charts]# kubectl create clusterrolebinding kubeapps-operator --clusterrole=cluster-admin --serviceaccount=ns-support:kubeapps-operator
```
```shell
[root@master-0 charts]# curl http://chartmuseum.kube.sz/api/charts
{"chartmuseum":[{"name":"chartmuseum","home":"https://github.com/helm/chartmuseum","version":"1.8.2","description":"Host your own Helm Chart Repository","keywords":["chartmuseum","helm","charts repo"],"maintainers":[{"name":"codefresh-io","email":"opensource@codefresh.io"},{"name":"cloudposse","email":"hello@cloudposse.com"},{"name":"chartmuseum","email":"chartmuseum@gmail.com"}],"icon":"https://raw.githubusercontent.com/helm/chartmuseum/master/logo2.png","apiVersion":"v1","appVersion":"0.8.0","urls":["charts/chartmuseum-1.8.2.tgz"],"created":"2018-12-24T07:05:57.685093316Z","digest":"8a2b578de87724ed3d2010ffa570bcec9aa577afeef5031a44f459dc9a0be367"}],"kubeapps":[{"name":"kubeapps","home":"https://kubeapps.com","sources":["https://github.com/kubeapps/kubeapps"],"version":"1.1.0","description":"Kubeapps is a dashboard for your Kubernetes cluster that makes it easy to deploy and manage applications in your cluster using Helm","keywords":["helm","dashboard","service catalog","deployment"],"maintainers":[{"name":"Bitnami","email":"containers@bitnami.com"},{"name":"prydonius","email":"adnan@bitnami.com"}],"icon":"https://raw.githubusercontent.com/kubeapps/kubeapps/master/docs/img/logo.png","apiVersion":"v1","appVersion":"v1.0.0","tillerVersion":"\u003e=2.10.0","urls":["charts/kubeapps-1.1.0.tgz"],"created":"2018-12-24T06:55:01.694090481Z","digest":"8193af29ffdb1665dec4e37d44d0501a94c6b29890949460ff8f196131708ea0"}]}

[root@master-0 charts]# kubectl get pods -o wide -n ns-support 
NAME                                                          READY   STATUS    RESTARTS   AGE   IP                NODE       NOMINATED NODE   READINESS GATES
chart-museum-chartmuseum-676f79c9db-5vs7m                     1/1     Running   0          87m   10.233.66.4       master-2   <none>           <none>
kubeapps-868f7d5c6c-7qzxt                                     1/1     Running   0          67m   10.233.64.7       master-0   <none>           <none>
kubeapps-868f7d5c6c-gsnrd                                     1/1     Running   0          67m   10.233.65.5       master-1   <none>           <none>
kubeapps-internal-apprepository-controller-79767c45c4-9gcbl   1/1     Running   0          67m   10.233.64.6       master-0   <none>           <none>
kubeapps-internal-chartsvc-6664d8f8d7-f5p8g                   1/1     Running   2          67m   10.233.65.7       master-1   <none>           <none>
kubeapps-internal-chartsvc-6664d8f8d7-vqnqk                   1/1     Running   2          67m   10.233.66.7       master-2   <none>           <none>
kubeapps-internal-dashboard-6f86c58d95-hfbhk                  1/1     Running   0          67m   10.233.66.6       master-2   <none>           <none>
kubeapps-internal-dashboard-6f86c58d95-l6trn                  1/1     Running   0          67m   10.233.65.6       master-1   <none>           <none>
kubeapps-internal-tiller-proxy-64786df647-6vkkg               1/1     Running   0          67m   10.233.65.8       master-1   <none>           <none>
kubeapps-internal-tiller-proxy-64786df647-kgsjv               1/1     Running   0          67m   10.233.66.5       master-2   <none>           <none>
kubeapps-mongodb-65ff777d57-knjrm                             1/1     Running   0          67m   10.233.64.5       master-0   <none>           <none>

[root@master-0 charts]# kubectl get svc -n ns-support 
NAME                                                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)     AGE
chart-museum-chartmuseum                                 ClusterIP   10.98.209.68     <none>        8080/TCP    95m
kubeapps                                                 ClusterIP   10.109.168.142   <none>        80/TCP      75m
kubeapps-internal-chartsvc                               ClusterIP   10.97.181.177    <none>        8080/TCP    75m
kubeapps-internal-dashboard                              ClusterIP   10.108.156.27    <none>        8080/TCP    75m
kubeapps-internal-tiller-proxy                           ClusterIP   10.98.66.151     <none>        8080/TCP    75m
kubeapps-mongodb                                         ClusterIP   10.107.180.148   <none>        27017/TCP   75m
```
![image](https://user-images.githubusercontent.com/22833023/50394476-ba16f180-0798-11e9-89eb-8701e75b8033.png)
![image](https://user-images.githubusercontent.com/22833023/50394488-d3b83900-0798-11e9-861c-8e1c346357fd.png)

Thanks for your help!

**Comment by chenlein** [comment]
The log of apprepository:
```
I1224 07:55:05.682352       1 controller.go:263] AppRepository 'inner-service' no longer exists so performing cleanup of charts from the DB
I1224 07:55:05.682481       1 controller.go:234] Successfully synced 'inner-service'
I1224 07:55:08.305450       1 controller.go:263] AppRepository 'charts' no longer exists so performing cleanup of charts from the DB
I1224 07:55:08.305540       1 controller.go:234] Successfully synced 'charts'
I1224 07:55:25.132109       1 controller.go:263] AppRepository 'museum' no longer exists so performing cleanup of charts from the DB
I1224 07:55:25.132203       1 controller.go:234] Successfully synced 'museum'
```
but I can get the chart's information by curl.

**Comment by chenlein** [comment]
I think this question may be related to the scope of the CRD. The `apprepository-crd.yaml` file is not defined the `scope` field. When the `apprepository-crd.yaml` is deployed, `scope` field is set to `Cluster` by default. At this time, I tried to delete helm release:
```shell
[root@master-0 charts]# helm delete --purge kubeapps
```
Waiting continuously..............

And then, I found this:
```shell
[root@master-0 ~]# kubectl logs -f -n ns-support      kubeapps-internal-apprepository-jobs-cleanup-sjzxk 
Error from server (Forbidden): apprepositories.kubeapps.com is forbidden: User "system:serviceaccount:ns-support:kubeapps-internal-apprepository-jobs-cleanup" cannot list resource "apprepositories" in API group "kubeapps.com" at the cluster scope
```
and the `controller.go` required the namespace filed:
```go
	// Get the AppRepository resource with this namespace/name
	apprepo, err := c.appreposLister.AppRepositories(namespace).Get(name)
	if err != nil {
		// The AppRepository resource may no longer exist, in which case we stop
		// processing.
		if errors.IsNotFound(err) {
			glog.Infof("AppRepository '%s' no longer exists so performing cleanup of charts from the DB", key)
			// Trigger a Job to perfrom the cleanup of the charts in the DB corresponding to deleted AppRepository
			_, err = c.kubeclientset.BatchV1().Jobs(namespace).Create(newCleanupJob(name, namespace))
			return nil
		}
		return fmt.Errorf("Error fetching object with key %s from store: %v", key, err)
	}
```
So, I modified the chart file, add the scope field for `apprepositories.kubeapps.com`:
```yaml
{{- if not (.Capabilities.APIVersions.Has "kubeapps.com/v1alpha1") -}}
# The condition above will be true if another instance of Kubeapps is
# already installed
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: apprepositories.kubeapps.com
  annotations:
    "helm.sh/hook": crd-install
  labels:
    app: {{ template "kubeapps.apprepository.fullname" . }}
    chart: {{ template "kubeapps.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  group: kubeapps.com
  scope: Namespaced
  names:
    kind: AppRepository
    plural: apprepositories
    shortNames:
    - apprepos
  version: v1alpha1
{{- end -}}
```
Finally, it work good!
