### ISSUE TITLE
Checkbox inputs in the binding creation doesn't seem to be sent correctly

### ISSUE THREAD

**Issue by arapulido** [kubeapps/kubeapps#990]
I have this Binding object description:

```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceBinding
metadata:
  name: user-storage-binding
spec:
  instanceRef:
    name: storage-instance-gcp
  parameters:
    serviceAccount: gcp-user-storage-example
    createServiceAccount: true
    roles:
      - roles/storage.objectCreator
      - roles/storage.objectViewer
```

If I create it using that YAML definition, the service account is created correctly (as I set createServiceAccount as true).

If I try to create a similar binding using Kubeapps:

<img width="520" alt="Screen Shot 2019-03-12 at 4 19 31 PM" src="https://user-images.githubusercontent.com/925437/54212069-ab5ff100-44e2-11e9-9810-084e6035d9ed.png">

I get the following error:

```
Bind call failed: operation "projects/774136762833/operations/71b21764-44d7-11e9-aed6-0a580a3c0405/1552402773527569072" failed: generic::invalid_argument: operation "projects/774136762833/operations/2168392e-44d7-11e9-aed6-0a580a3c0405/1552402785656614456" failed: generic::invalid_argument: Operation "operation-1552402786065-583e6f09c9c21-40be9258-d977932b" failed with
: [{"code":"RESOURCE_ERROR","location":"/deployments/i2e287c24-a0e3-4724-a459-7235658ae1a5/resources/chartmuseumara-82bfeec5-3779-4188-ae90-78fb12873935","message":"{\"ResourceType\":\"storage.v1.bucket\",\"ResourceErrorCode\":\"400\",\"ResourceErrorMessage\":{\"code\":400,\"errors\":[{\"domain\":\"global\",\"message\":\"Service account gcp-user-storage-example-ara@bitnamigcetest2.iam.gserviceaccount.com does not exist.\",\"reason\":\"invalid\"}],\"message\":\"Service account gcp-user-storage-example-ara@bitnamigcetest2.iam.gserviceaccount.com does not exist.\",\"statusMessage\":\"Bad Request\",\"requestPath\":\"https://www.googleapis.com/storage/v1/b/chartmuseumara-82bfeec5-3779-4188-ae90-78fb12873935/iam\",\"httpMethod\":\"PUT\"}}"}]
```
From that error I guess that it didn't try to create the service account and tried to find it (and failed).
